<?php

/**
 * BaseComapnyFavouriteList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $company_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $sfGuardUser
 * @property Empresa $Empresa
 * 
 * @method integer              getUserId()      Returns the current record's "user_id" value
 * @method integer              getCompanyId()   Returns the current record's "company_id" value
 * @method timestamp            getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp            getUpdatedAt()   Returns the current record's "updated_at" value
 * @method sfGuardUser          getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Empresa              getEmpresa()     Returns the current record's "Empresa" value
 * @method ComapnyFavouriteList setUserId()      Sets the current record's "user_id" value
 * @method ComapnyFavouriteList setCompanyId()   Sets the current record's "company_id" value
 * @method ComapnyFavouriteList setCreatedAt()   Sets the current record's "created_at" value
 * @method ComapnyFavouriteList setUpdatedAt()   Sets the current record's "updated_at" value
 * @method ComapnyFavouriteList setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method ComapnyFavouriteList setEmpresa()     Sets the current record's "Empresa" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComapnyFavouriteList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_favourite_list');
        $this->hasColumn('user_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('company_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Empresa', array(
             'local' => 'company_id',
             'foreign' => 'id'));
    }
}