<?php

/**
 * BaseMetodoBanco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $tipo_documento_id
 * @property string $nifnie
 * @property string $titular_name
 * @property string $surname1
 * @property string $surname2
 * @property string $cuenta_entidad
 * @property string $cuenta_oficina
 * @property string $cuenta_dc
 * @property string $cuenta_numero
 * @property sfGuardUser $sfGuardUser
 * @property TipoDocumento $TipoDocumento
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method integer       getUserId()            Returns the current record's "user_id" value
 * @method integer       getTipoDocumentoId()   Returns the current record's "tipo_documento_id" value
 * @method string        getNifnie()            Returns the current record's "nifnie" value
 * @method string        getTitularName()       Returns the current record's "titular_name" value
 * @method string        getSurname1()          Returns the current record's "surname1" value
 * @method string        getSurname2()          Returns the current record's "surname2" value
 * @method string        getCuentaEntidad()     Returns the current record's "cuenta_entidad" value
 * @method string        getCuentaOficina()     Returns the current record's "cuenta_oficina" value
 * @method string        getCuentaDc()          Returns the current record's "cuenta_dc" value
 * @method string        getCuentaNumero()      Returns the current record's "cuenta_numero" value
 * @method sfGuardUser   getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method TipoDocumento getTipoDocumento()     Returns the current record's "TipoDocumento" value
 * @method MetodoBanco   setId()                Sets the current record's "id" value
 * @method MetodoBanco   setUserId()            Sets the current record's "user_id" value
 * @method MetodoBanco   setTipoDocumentoId()   Sets the current record's "tipo_documento_id" value
 * @method MetodoBanco   setNifnie()            Sets the current record's "nifnie" value
 * @method MetodoBanco   setTitularName()       Sets the current record's "titular_name" value
 * @method MetodoBanco   setSurname1()          Sets the current record's "surname1" value
 * @method MetodoBanco   setSurname2()          Sets the current record's "surname2" value
 * @method MetodoBanco   setCuentaEntidad()     Sets the current record's "cuenta_entidad" value
 * @method MetodoBanco   setCuentaOficina()     Sets the current record's "cuenta_oficina" value
 * @method MetodoBanco   setCuentaDc()          Sets the current record's "cuenta_dc" value
 * @method MetodoBanco   setCuentaNumero()      Sets the current record's "cuenta_numero" value
 * @method MetodoBanco   setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method MetodoBanco   setTipoDocumento()     Sets the current record's "TipoDocumento" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMetodoBanco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('metodo_banco');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('tipo_documento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nifnie', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('titular_name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('surname1', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('surname2', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('cuenta_entidad', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuenta_oficina', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuenta_dc', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('cuenta_numero', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('TipoDocumento', array(
             'local' => 'tipo_documento_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));
    }
}