<?php

/**
 * BaseConcursoArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $concurso_id
 * @property string $file
 * @property Concurso $Concurso
 * 
 * @method integer         getConcursoId()  Returns the current record's "concurso_id" value
 * @method string          getFile()        Returns the current record's "file" value
 * @method Concurso        getConcurso()    Returns the current record's "Concurso" value
 * @method ConcursoArchivo setConcursoId()  Sets the current record's "concurso_id" value
 * @method ConcursoArchivo setFile()        Sets the current record's "file" value
 * @method ConcursoArchivo setConcurso()    Sets the current record's "Concurso" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcursoArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concurso_archivo');
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}