<?php

/**
 * BaseComentarioCp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $contenido
 * @property integer $user_id
 * @property integer $concurso_cp_id
 * @property integer $contribucion_cp_id
 * @property integer $parent_id
 * @property ComentarioCp $Parent
 * @property sfGuardUser $sfGuardUser
 * @property ConcursoCp $ConcursoCp
 * @property ContribucionCp $ContribucionCp
 * @property Doctrine_Collection $Subcomentario
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getContenido()          Returns the current record's "contenido" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method integer             getConcursoCpId()       Returns the current record's "concurso_cp_id" value
 * @method integer             getContribucionCpId()   Returns the current record's "contribucion_cp_id" value
 * @method integer             getParentId()           Returns the current record's "parent_id" value
 * @method ComentarioCp        getParent()             Returns the current record's "Parent" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method ConcursoCp          getConcursoCp()         Returns the current record's "ConcursoCp" value
 * @method ContribucionCp      getContribucionCp()     Returns the current record's "ContribucionCp" value
 * @method Doctrine_Collection getSubcomentario()      Returns the current record's "Subcomentario" collection
 * @method ComentarioCp        setName()               Sets the current record's "name" value
 * @method ComentarioCp        setContenido()          Sets the current record's "contenido" value
 * @method ComentarioCp        setUserId()             Sets the current record's "user_id" value
 * @method ComentarioCp        setConcursoCpId()       Sets the current record's "concurso_cp_id" value
 * @method ComentarioCp        setContribucionCpId()   Sets the current record's "contribucion_cp_id" value
 * @method ComentarioCp        setParentId()           Sets the current record's "parent_id" value
 * @method ComentarioCp        setParent()             Sets the current record's "Parent" value
 * @method ComentarioCp        setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method ComentarioCp        setConcursoCp()         Sets the current record's "ConcursoCp" value
 * @method ComentarioCp        setContribucionCp()     Sets the current record's "ContribucionCp" value
 * @method ComentarioCp        setSubcomentario()      Sets the current record's "Subcomentario" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentarioCp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario_cp');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('concurso_cp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contribucion_cp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ComentarioCp as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ConcursoCp', array(
             'local' => 'concurso_cp_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ContribucionCp', array(
             'local' => 'contribucion_cp_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('ComentarioCp as Subcomentario', array(
             'local' => 'id',
             'foreign' => 'parent_id'));
    }
}