<?php

/**
 * BaseContratanos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status
 * @property varchar $name
 * @property integer $road_type_id
 * @property varchar $cif
 * @property varchar $actividad
 * @property varchar $nombre
 * @property varchar $apellido1
 * @property varchar $apellido2
 * @property varchar $cargo
 * @property varchar $email
 * @property varchar $phone
 * @property varchar $direccion
 * @property varchar $num
 * @property varchar $piso
 * @property varchar $puerta
 * @property varchar $cp
 * @property varchar $states_id
 * @property varchar $city_id
 * @property varchar $ayudar
 * @property varchar $servicio
 * @property varchar $antes
 * @property varchar $what
 * @property varchar $empresa
 * @property boolean $form_type
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer     getStatus()       Returns the current record's "status" value
 * @method varchar     getName()         Returns the current record's "name" value
 * @method integer     getRoadTypeId()   Returns the current record's "road_type_id" value
 * @method varchar     getCif()          Returns the current record's "cif" value
 * @method varchar     getActividad()    Returns the current record's "actividad" value
 * @method varchar     getNombre()       Returns the current record's "nombre" value
 * @method varchar     getApellido1()    Returns the current record's "apellido1" value
 * @method varchar     getApellido2()    Returns the current record's "apellido2" value
 * @method varchar     getCargo()        Returns the current record's "cargo" value
 * @method varchar     getEmail()        Returns the current record's "email" value
 * @method varchar     getPhone()        Returns the current record's "phone" value
 * @method varchar     getDireccion()    Returns the current record's "direccion" value
 * @method varchar     getNum()          Returns the current record's "num" value
 * @method varchar     getPiso()         Returns the current record's "piso" value
 * @method varchar     getPuerta()       Returns the current record's "puerta" value
 * @method varchar     getCp()           Returns the current record's "cp" value
 * @method varchar     getStatesId()     Returns the current record's "states_id" value
 * @method varchar     getCityId()       Returns the current record's "city_id" value
 * @method varchar     getAyudar()       Returns the current record's "ayudar" value
 * @method varchar     getServicio()     Returns the current record's "servicio" value
 * @method varchar     getAntes()        Returns the current record's "antes" value
 * @method varchar     getWhat()         Returns the current record's "what" value
 * @method varchar     getEmpresa()      Returns the current record's "empresa" value
 * @method boolean     getFormType()     Returns the current record's "form_type" value
 * @method timestamp   getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Contratanos setStatus()       Sets the current record's "status" value
 * @method Contratanos setName()         Sets the current record's "name" value
 * @method Contratanos setRoadTypeId()   Sets the current record's "road_type_id" value
 * @method Contratanos setCif()          Sets the current record's "cif" value
 * @method Contratanos setActividad()    Sets the current record's "actividad" value
 * @method Contratanos setNombre()       Sets the current record's "nombre" value
 * @method Contratanos setApellido1()    Sets the current record's "apellido1" value
 * @method Contratanos setApellido2()    Sets the current record's "apellido2" value
 * @method Contratanos setCargo()        Sets the current record's "cargo" value
 * @method Contratanos setEmail()        Sets the current record's "email" value
 * @method Contratanos setPhone()        Sets the current record's "phone" value
 * @method Contratanos setDireccion()    Sets the current record's "direccion" value
 * @method Contratanos setNum()          Sets the current record's "num" value
 * @method Contratanos setPiso()         Sets the current record's "piso" value
 * @method Contratanos setPuerta()       Sets the current record's "puerta" value
 * @method Contratanos setCp()           Sets the current record's "cp" value
 * @method Contratanos setStatesId()     Sets the current record's "states_id" value
 * @method Contratanos setCityId()       Sets the current record's "city_id" value
 * @method Contratanos setAyudar()       Sets the current record's "ayudar" value
 * @method Contratanos setServicio()     Sets the current record's "servicio" value
 * @method Contratanos setAntes()        Sets the current record's "antes" value
 * @method Contratanos setWhat()         Sets the current record's "what" value
 * @method Contratanos setEmpresa()      Sets the current record's "empresa" value
 * @method Contratanos setFormType()     Sets the current record's "form_type" value
 * @method Contratanos setCreatedAt()    Sets the current record's "created_at" value
 * @method Contratanos setUpdatedAt()    Sets the current record's "updated_at" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContratanos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contratanos');
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 5,
             ));
        $this->hasColumn('name', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('road_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('cif', 'varchar', 9, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 9,
             ));
        $this->hasColumn('actividad', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('nombre', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('apellido1', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('apellido2', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('cargo', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('email', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('phone', 'varchar', 9, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 9,
             ));
        $this->hasColumn('direccion', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('num', 'varchar', 6, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('piso', 'varchar', 3, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('puerta', 'varchar', 6, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('cp', 'varchar', 5, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('states_id', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('city_id', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('ayudar', 'varchar', 850, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 850,
             ));
        $this->hasColumn('servicio', 'varchar', 100, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('antes', 'varchar', 10, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('what', 'varchar', 100, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('empresa', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('form_type', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}