<?php

/**
 * BaseMesaredondaPonencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $asunto
 * @property integer $mesa_redonda_id
 * @property string $plan_accion
 * @property string $resumen
 * @property date $fecha_alta
 * @property integer $mesaredonda_estado_id
 * @property MesaRedonda $MesaRedonda
 * @property MesaredondaEstado $MesaredondaEstado
 * @property Doctrine_Collection $MesaredondaReferendum
 * 
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getAsunto()                Returns the current record's "asunto" value
 * @method integer             getMesaRedondaId()         Returns the current record's "mesa_redonda_id" value
 * @method string              getPlanAccion()            Returns the current record's "plan_accion" value
 * @method string              getResumen()               Returns the current record's "resumen" value
 * @method date                getFechaAlta()             Returns the current record's "fecha_alta" value
 * @method integer             getMesaredondaEstadoId()   Returns the current record's "mesaredonda_estado_id" value
 * @method MesaRedonda         getMesaRedonda()           Returns the current record's "MesaRedonda" value
 * @method MesaredondaEstado   getMesaredondaEstado()     Returns the current record's "MesaredondaEstado" value
 * @method Doctrine_Collection getMesaredondaReferendum() Returns the current record's "MesaredondaReferendum" collection
 * @method MesaredondaPonencia setName()                  Sets the current record's "name" value
 * @method MesaredondaPonencia setAsunto()                Sets the current record's "asunto" value
 * @method MesaredondaPonencia setMesaRedondaId()         Sets the current record's "mesa_redonda_id" value
 * @method MesaredondaPonencia setPlanAccion()            Sets the current record's "plan_accion" value
 * @method MesaredondaPonencia setResumen()               Sets the current record's "resumen" value
 * @method MesaredondaPonencia setFechaAlta()             Sets the current record's "fecha_alta" value
 * @method MesaredondaPonencia setMesaredondaEstadoId()   Sets the current record's "mesaredonda_estado_id" value
 * @method MesaredondaPonencia setMesaRedonda()           Sets the current record's "MesaRedonda" value
 * @method MesaredondaPonencia setMesaredondaEstado()     Sets the current record's "MesaredondaEstado" value
 * @method MesaredondaPonencia setMesaredondaReferendum() Sets the current record's "MesaredondaReferendum" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMesaredondaPonencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mesaredonda_ponencia');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('asunto', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('mesa_redonda_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('plan_accion', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2147483647,
             ));
        $this->hasColumn('resumen', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2147483647,
             ));
        $this->hasColumn('fecha_alta', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('mesaredonda_estado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MesaRedonda', array(
             'local' => 'mesa_redonda_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('MesaredondaEstado', array(
             'local' => 'mesaredonda_estado_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('MesaredondaReferendum', array(
             'local' => 'id',
             'foreign' => 'mesaredonda_ponencia_id'));
    }
}