<?php

/**
 * BaseStates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $orden
 * @property Doctrine_Collection $Concurso
 * @property Doctrine_Collection $Pd
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $sfGuardUserProfile
 * @property Doctrine_Collection $ConcursoCp
 * @property Doctrine_Collection $UserNotification
 * @property Doctrine_Collection $GiftRedemption
 * @property Doctrine_Collection $Profesional
 * @property Doctrine_Collection $ProfesionalLetter
 * @property Doctrine_Collection $Empresa
 * @property Doctrine_Collection $CompanyCaseStudy
 * @property Doctrine_Collection $UserCompanyCaseStudy
 * @property Doctrine_Collection $UserCompanyCaseStudyRequest
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method integer             getOrden()                       Returns the current record's "orden" value
 * @method Doctrine_Collection getConcurso()                    Returns the current record's "Concurso" collection
 * @method Doctrine_Collection getPd()                          Returns the current record's "Pd" collection
 * @method Doctrine_Collection getCity()                        Returns the current record's "City" collection
 * @method Doctrine_Collection getSfGuardUserProfile()          Returns the current record's "sfGuardUserProfile" collection
 * @method Doctrine_Collection getConcursoCp()                  Returns the current record's "ConcursoCp" collection
 * @method Doctrine_Collection getUserNotification()            Returns the current record's "UserNotification" collection
 * @method Doctrine_Collection getGiftRedemption()              Returns the current record's "GiftRedemption" collection
 * @method Doctrine_Collection getProfesional()                 Returns the current record's "Profesional" collection
 * @method Doctrine_Collection getProfesionalLetter()           Returns the current record's "ProfesionalLetter" collection
 * @method Doctrine_Collection getEmpresa()                     Returns the current record's "Empresa" collection
 * @method Doctrine_Collection getCompanyCaseStudy()            Returns the current record's "CompanyCaseStudy" collection
 * @method Doctrine_Collection getUserCompanyCaseStudy()        Returns the current record's "UserCompanyCaseStudy" collection
 * @method Doctrine_Collection getUserCompanyCaseStudyRequest() Returns the current record's "UserCompanyCaseStudyRequest" collection
 * @method States              setName()                        Sets the current record's "name" value
 * @method States              setOrden()                       Sets the current record's "orden" value
 * @method States              setConcurso()                    Sets the current record's "Concurso" collection
 * @method States              setPd()                          Sets the current record's "Pd" collection
 * @method States              setCity()                        Sets the current record's "City" collection
 * @method States              setSfGuardUserProfile()          Sets the current record's "sfGuardUserProfile" collection
 * @method States              setConcursoCp()                  Sets the current record's "ConcursoCp" collection
 * @method States              setUserNotification()            Sets the current record's "UserNotification" collection
 * @method States              setGiftRedemption()              Sets the current record's "GiftRedemption" collection
 * @method States              setProfesional()                 Sets the current record's "Profesional" collection
 * @method States              setProfesionalLetter()           Sets the current record's "ProfesionalLetter" collection
 * @method States              setEmpresa()                     Sets the current record's "Empresa" collection
 * @method States              setCompanyCaseStudy()            Sets the current record's "CompanyCaseStudy" collection
 * @method States              setUserCompanyCaseStudy()        Sets the current record's "UserCompanyCaseStudy" collection
 * @method States              setUserCompanyCaseStudyRequest() Sets the current record's "UserCompanyCaseStudyRequest" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('states');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('orden', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Concurso', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('Pd', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('City', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('ConcursoCp', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('UserNotification', array(
             'local' => 'id',
             'foreign' => 'concurso_empresa_provincia_id'));

        $this->hasMany('GiftRedemption', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('Profesional', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('ProfesionalLetter', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('Empresa', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('CompanyCaseStudy', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('UserCompanyCaseStudy', array(
             'local' => 'id',
             'foreign' => 'states_id'));

        $this->hasMany('UserCompanyCaseStudyRequest', array(
             'local' => 'id',
             'foreign' => 'states_id'));
    }
}