<?php

/**
 * BaseUserCompanyCaseStudyRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status
 * @property string $user_name
 * @property integer $user_id
 * @property string $name
 * @property string $homepage
 * @property integer $road_type_id
 * @property string $direccion
 * @property string $numero
 * @property string $piso
 * @property string $puerta
 * @property integer $states_id
 * @property integer $city_id
 * @property string $cp
 * @property integer $empresa_sector_uno_id
 * @property integer $empresa_sector_dos_id
 * @property integer $empresa_sector_tres_id
 * @property varchar $description
 * @property varchar $summary
 * @property varchar $file1
 * @property varchar $file2
 * @property varchar $file3
 * @property varchar $file4
 * @property varchar $logo
 * @property sfGuardUser $User
 * @property States $States
 * @property City $Localidad
 * @property EmpresaSectorUno $EmpresaSectorUno
 * @property EmpresaSectorDos $EmpresaSectorDos
 * @property EmpresaSectorTres $EmpresaSectorTres
 * @property RoadType $RoadType
 * 
 * @method integer                     getStatus()                 Returns the current record's "status" value
 * @method string                      getUserName()               Returns the current record's "user_name" value
 * @method integer                     getUserId()                 Returns the current record's "user_id" value
 * @method string                      getName()                   Returns the current record's "name" value
 * @method string                      getHomepage()               Returns the current record's "homepage" value
 * @method integer                     getRoadTypeId()             Returns the current record's "road_type_id" value
 * @method string                      getDireccion()              Returns the current record's "direccion" value
 * @method string                      getNumero()                 Returns the current record's "numero" value
 * @method string                      getPiso()                   Returns the current record's "piso" value
 * @method string                      getPuerta()                 Returns the current record's "puerta" value
 * @method integer                     getStatesId()               Returns the current record's "states_id" value
 * @method integer                     getCityId()                 Returns the current record's "city_id" value
 * @method string                      getCp()                     Returns the current record's "cp" value
 * @method integer                     getEmpresaSectorUnoId()     Returns the current record's "empresa_sector_uno_id" value
 * @method integer                     getEmpresaSectorDosId()     Returns the current record's "empresa_sector_dos_id" value
 * @method integer                     getEmpresaSectorTresId()    Returns the current record's "empresa_sector_tres_id" value
 * @method varchar                     getDescription()            Returns the current record's "description" value
 * @method varchar                     getSummary()                Returns the current record's "summary" value
 * @method varchar                     getFile1()                  Returns the current record's "file1" value
 * @method varchar                     getFile2()                  Returns the current record's "file2" value
 * @method varchar                     getFile3()                  Returns the current record's "file3" value
 * @method varchar                     getFile4()                  Returns the current record's "file4" value
 * @method varchar                     getLogo()                   Returns the current record's "logo" value
 * @method sfGuardUser                 getUser()                   Returns the current record's "User" value
 * @method States                      getStates()                 Returns the current record's "States" value
 * @method City                        getLocalidad()              Returns the current record's "Localidad" value
 * @method EmpresaSectorUno            getEmpresaSectorUno()       Returns the current record's "EmpresaSectorUno" value
 * @method EmpresaSectorDos            getEmpresaSectorDos()       Returns the current record's "EmpresaSectorDos" value
 * @method EmpresaSectorTres           getEmpresaSectorTres()      Returns the current record's "EmpresaSectorTres" value
 * @method RoadType                    getRoadType()               Returns the current record's "RoadType" value
 * @method UserCompanyCaseStudyRequest setStatus()                 Sets the current record's "status" value
 * @method UserCompanyCaseStudyRequest setUserName()               Sets the current record's "user_name" value
 * @method UserCompanyCaseStudyRequest setUserId()                 Sets the current record's "user_id" value
 * @method UserCompanyCaseStudyRequest setName()                   Sets the current record's "name" value
 * @method UserCompanyCaseStudyRequest setHomepage()               Sets the current record's "homepage" value
 * @method UserCompanyCaseStudyRequest setRoadTypeId()             Sets the current record's "road_type_id" value
 * @method UserCompanyCaseStudyRequest setDireccion()              Sets the current record's "direccion" value
 * @method UserCompanyCaseStudyRequest setNumero()                 Sets the current record's "numero" value
 * @method UserCompanyCaseStudyRequest setPiso()                   Sets the current record's "piso" value
 * @method UserCompanyCaseStudyRequest setPuerta()                 Sets the current record's "puerta" value
 * @method UserCompanyCaseStudyRequest setStatesId()               Sets the current record's "states_id" value
 * @method UserCompanyCaseStudyRequest setCityId()                 Sets the current record's "city_id" value
 * @method UserCompanyCaseStudyRequest setCp()                     Sets the current record's "cp" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorUnoId()     Sets the current record's "empresa_sector_uno_id" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorDosId()     Sets the current record's "empresa_sector_dos_id" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorTresId()    Sets the current record's "empresa_sector_tres_id" value
 * @method UserCompanyCaseStudyRequest setDescription()            Sets the current record's "description" value
 * @method UserCompanyCaseStudyRequest setSummary()                Sets the current record's "summary" value
 * @method UserCompanyCaseStudyRequest setFile1()                  Sets the current record's "file1" value
 * @method UserCompanyCaseStudyRequest setFile2()                  Sets the current record's "file2" value
 * @method UserCompanyCaseStudyRequest setFile3()                  Sets the current record's "file3" value
 * @method UserCompanyCaseStudyRequest setFile4()                  Sets the current record's "file4" value
 * @method UserCompanyCaseStudyRequest setLogo()                   Sets the current record's "logo" value
 * @method UserCompanyCaseStudyRequest setUser()                   Sets the current record's "User" value
 * @method UserCompanyCaseStudyRequest setStates()                 Sets the current record's "States" value
 * @method UserCompanyCaseStudyRequest setLocalidad()              Sets the current record's "Localidad" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorUno()       Sets the current record's "EmpresaSectorUno" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorDos()       Sets the current record's "EmpresaSectorDos" value
 * @method UserCompanyCaseStudyRequest setEmpresaSectorTres()      Sets the current record's "EmpresaSectorTres" value
 * @method UserCompanyCaseStudyRequest setRoadType()               Sets the current record's "RoadType" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserCompanyCaseStudyRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_company_case_study_request');
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 5,
             ));
        $this->hasColumn('user_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('user_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('homepage', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('road_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('direccion', 'string', 70, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 70,
             ));
        $this->hasColumn('numero', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('piso', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('puerta', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('states_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('cp', 'string', 5, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('empresa_sector_uno_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_sector_dos_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_sector_tres_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('description', 'varchar', 43000, array(
             'type' => 'varchar',
             'length' => 43000,
             ));
        $this->hasColumn('summary', 'varchar', 8300, array(
             'type' => 'varchar',
             'length' => 8300,
             ));
        $this->hasColumn('file1', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file2', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file3', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file4', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('logo', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('States', array(
             'local' => 'states_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('City as Localidad', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorUno', array(
             'local' => 'empresa_sector_uno_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorDos', array(
             'local' => 'empresa_sector_dos_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorTres', array(
             'local' => 'empresa_sector_tres_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('RoadType', array(
             'local' => 'road_type_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}