<?php

/**
 * BaseEmpresaSectorUno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * @property integer $orden
 * @property string $image
 * @property Doctrine_Collection $EmpresaSectorDos
 * @property Doctrine_Collection $EmpresaSectorTres
 * @property Doctrine_Collection $Empresa
 * @property Doctrine_Collection $EmpresasDestacadas
 * @property Doctrine_Collection $CompanyCaseStudy
 * @property Doctrine_Collection $UserCompanyCaseStudy
 * @property Doctrine_Collection $UserCompanyCaseStudyRequest
 * @property Doctrine_Collection $ListaCuestionario
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getValue()                       Returns the current record's "value" value
 * @method integer             getOrden()                       Returns the current record's "orden" value
 * @method string              getImage()                       Returns the current record's "image" value
 * @method Doctrine_Collection getEmpresaSectorDos()            Returns the current record's "EmpresaSectorDos" collection
 * @method Doctrine_Collection getEmpresaSectorTres()           Returns the current record's "EmpresaSectorTres" collection
 * @method Doctrine_Collection getEmpresa()                     Returns the current record's "Empresa" collection
 * @method Doctrine_Collection getEmpresasDestacadas()          Returns the current record's "EmpresasDestacadas" collection
 * @method Doctrine_Collection getCompanyCaseStudy()            Returns the current record's "CompanyCaseStudy" collection
 * @method Doctrine_Collection getUserCompanyCaseStudy()        Returns the current record's "UserCompanyCaseStudy" collection
 * @method Doctrine_Collection getUserCompanyCaseStudyRequest() Returns the current record's "UserCompanyCaseStudyRequest" collection
 * @method Doctrine_Collection getListaCuestionario()           Returns the current record's "ListaCuestionario" collection
 * @method EmpresaSectorUno    setName()                        Sets the current record's "name" value
 * @method EmpresaSectorUno    setValue()                       Sets the current record's "value" value
 * @method EmpresaSectorUno    setOrden()                       Sets the current record's "orden" value
 * @method EmpresaSectorUno    setImage()                       Sets the current record's "image" value
 * @method EmpresaSectorUno    setEmpresaSectorDos()            Sets the current record's "EmpresaSectorDos" collection
 * @method EmpresaSectorUno    setEmpresaSectorTres()           Sets the current record's "EmpresaSectorTres" collection
 * @method EmpresaSectorUno    setEmpresa()                     Sets the current record's "Empresa" collection
 * @method EmpresaSectorUno    setEmpresasDestacadas()          Sets the current record's "EmpresasDestacadas" collection
 * @method EmpresaSectorUno    setCompanyCaseStudy()            Sets the current record's "CompanyCaseStudy" collection
 * @method EmpresaSectorUno    setUserCompanyCaseStudy()        Sets the current record's "UserCompanyCaseStudy" collection
 * @method EmpresaSectorUno    setUserCompanyCaseStudyRequest() Sets the current record's "UserCompanyCaseStudyRequest" collection
 * @method EmpresaSectorUno    setListaCuestionario()           Sets the current record's "ListaCuestionario" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpresaSectorUno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresa_sector_uno');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('value', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EmpresaSectorDos', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('EmpresaSectorTres', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('Empresa', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('EmpresaDestacada as EmpresasDestacadas', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('CompanyCaseStudy', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('UserCompanyCaseStudy', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('UserCompanyCaseStudyRequest', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $this->hasMany('ListaCuestionario', array(
             'local' => 'id',
             'foreign' => 'empresa_sector_uno_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'id',
              1 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}