<?php

/**
 * BaseProductoTipoUno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $orden
 * @property string $name
 * @property string $image
 * @property Doctrine_Collection $ProductoTipoDos
 * @property Doctrine_Collection $ProductoTipoTres
 * @property Doctrine_Collection $Producto
 * @property Doctrine_Collection $ProductCaseStudy
 * @property Doctrine_Collection $UserProductCaseStudy
 * @property Doctrine_Collection $UserProductCaseStudyRequest
 * @property Doctrine_Collection $ListaCuestionario
 * 
 * @method integer             getOrden()                       Returns the current record's "orden" value
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getImage()                       Returns the current record's "image" value
 * @method Doctrine_Collection getProductoTipoDos()             Returns the current record's "ProductoTipoDos" collection
 * @method Doctrine_Collection getProductoTipoTres()            Returns the current record's "ProductoTipoTres" collection
 * @method Doctrine_Collection getProducto()                    Returns the current record's "Producto" collection
 * @method Doctrine_Collection getProductCaseStudy()            Returns the current record's "ProductCaseStudy" collection
 * @method Doctrine_Collection getUserProductCaseStudy()        Returns the current record's "UserProductCaseStudy" collection
 * @method Doctrine_Collection getUserProductCaseStudyRequest() Returns the current record's "UserProductCaseStudyRequest" collection
 * @method Doctrine_Collection getListaCuestionario()           Returns the current record's "ListaCuestionario" collection
 * @method ProductoTipoUno     setOrden()                       Sets the current record's "orden" value
 * @method ProductoTipoUno     setName()                        Sets the current record's "name" value
 * @method ProductoTipoUno     setImage()                       Sets the current record's "image" value
 * @method ProductoTipoUno     setProductoTipoDos()             Sets the current record's "ProductoTipoDos" collection
 * @method ProductoTipoUno     setProductoTipoTres()            Sets the current record's "ProductoTipoTres" collection
 * @method ProductoTipoUno     setProducto()                    Sets the current record's "Producto" collection
 * @method ProductoTipoUno     setProductCaseStudy()            Sets the current record's "ProductCaseStudy" collection
 * @method ProductoTipoUno     setUserProductCaseStudy()        Sets the current record's "UserProductCaseStudy" collection
 * @method ProductoTipoUno     setUserProductCaseStudyRequest() Sets the current record's "UserProductCaseStudyRequest" collection
 * @method ProductoTipoUno     setListaCuestionario()           Sets the current record's "ListaCuestionario" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductoTipoUno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_tipo_uno');
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductoTipoDos', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('ProductoTipoTres', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('ProductCaseStudy', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('UserProductCaseStudy', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('UserProductCaseStudyRequest', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $this->hasMany('ListaCuestionario', array(
             'local' => 'id',
             'foreign' => 'producto_tipo_uno_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'id',
              1 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}