<?php

/**
 * BaseFichero
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $file
 * @property integer $contribucion_id
 * @property Contribucion $Contribucion
 * 
 * @method string       getName()            Returns the current record's "name" value
 * @method string       getFile()            Returns the current record's "file" value
 * @method integer      getContribucionId()  Returns the current record's "contribucion_id" value
 * @method Contribucion getContribucion()    Returns the current record's "Contribucion" value
 * @method Fichero      setName()            Sets the current record's "name" value
 * @method Fichero      setFile()            Sets the current record's "file" value
 * @method Fichero      setContribucionId()  Sets the current record's "contribucion_id" value
 * @method Fichero      setContribucion()    Sets the current record's "Contribucion" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFichero extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fichero');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contribucion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contribucion', array(
             'local' => 'contribucion_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}