<?php

/**
 * BaseUserNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $colaborador_contribuye_value
 * @property boolean $concurso_empresa_value
 * @property string $concurso_empresa_nombre
 * @property integer $concurso_empresa_provincia_id
 * @property integer $concurso_empresa_ciudad_id
 * @property boolean $concurso_producto_value
 * @property string $concurso_producto_nombre
 * @property string $concurso_producto_marca
 * @property boolean $lista_blanca_value
 * @property boolean $lista_negra_value
 * @property boolean $publica_profesional_value
 * @property boolean $publica_recomend_disaprov_value
 * @property string $hash
 * @property States $States
 * @property sfGuardUser $User
 * @property City $City
 * 
 * @method integer          getUserId()                          Returns the current record's "user_id" value
 * @method boolean          getColaboradorContribuyeValue()      Returns the current record's "colaborador_contribuye_value" value
 * @method boolean          getConcursoEmpresaValue()            Returns the current record's "concurso_empresa_value" value
 * @method string           getConcursoEmpresaNombre()           Returns the current record's "concurso_empresa_nombre" value
 * @method integer          getConcursoEmpresaProvinciaId()      Returns the current record's "concurso_empresa_provincia_id" value
 * @method integer          getConcursoEmpresaCiudadId()         Returns the current record's "concurso_empresa_ciudad_id" value
 * @method boolean          getConcursoProductoValue()           Returns the current record's "concurso_producto_value" value
 * @method string           getConcursoProductoNombre()          Returns the current record's "concurso_producto_nombre" value
 * @method string           getConcursoProductoMarca()           Returns the current record's "concurso_producto_marca" value
 * @method boolean          getListaBlancaValue()                Returns the current record's "lista_blanca_value" value
 * @method boolean          getListaNegraValue()                 Returns the current record's "lista_negra_value" value
 * @method boolean          getPublicaProfesionalValue()         Returns the current record's "publica_profesional_value" value
 * @method boolean          getPublicaRecomendDisaprovValue()    Returns the current record's "publica_recomend_disaprov_value" value
 * @method string           getHash()                            Returns the current record's "hash" value
 * @method States           getStates()                          Returns the current record's "States" value
 * @method sfGuardUser      getUser()                            Returns the current record's "User" value
 * @method City             getCity()                            Returns the current record's "City" value
 * @method UserNotification setUserId()                          Sets the current record's "user_id" value
 * @method UserNotification setColaboradorContribuyeValue()      Sets the current record's "colaborador_contribuye_value" value
 * @method UserNotification setConcursoEmpresaValue()            Sets the current record's "concurso_empresa_value" value
 * @method UserNotification setConcursoEmpresaNombre()           Sets the current record's "concurso_empresa_nombre" value
 * @method UserNotification setConcursoEmpresaProvinciaId()      Sets the current record's "concurso_empresa_provincia_id" value
 * @method UserNotification setConcursoEmpresaCiudadId()         Sets the current record's "concurso_empresa_ciudad_id" value
 * @method UserNotification setConcursoProductoValue()           Sets the current record's "concurso_producto_value" value
 * @method UserNotification setConcursoProductoNombre()          Sets the current record's "concurso_producto_nombre" value
 * @method UserNotification setConcursoProductoMarca()           Sets the current record's "concurso_producto_marca" value
 * @method UserNotification setListaBlancaValue()                Sets the current record's "lista_blanca_value" value
 * @method UserNotification setListaNegraValue()                 Sets the current record's "lista_negra_value" value
 * @method UserNotification setPublicaProfesionalValue()         Sets the current record's "publica_profesional_value" value
 * @method UserNotification setPublicaRecomendDisaprovValue()    Sets the current record's "publica_recomend_disaprov_value" value
 * @method UserNotification setHash()                            Sets the current record's "hash" value
 * @method UserNotification setStates()                          Sets the current record's "States" value
 * @method UserNotification setUser()                            Sets the current record's "User" value
 * @method UserNotification setCity()                            Sets the current record's "City" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_notification');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('colaborador_contribuye_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('concurso_empresa_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('concurso_empresa_nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('concurso_empresa_provincia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('concurso_empresa_ciudad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('concurso_producto_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('concurso_producto_nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('concurso_producto_marca', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('lista_blanca_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('lista_negra_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('publica_profesional_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('publica_recomend_disaprov_value', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('hash', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('States', array(
             'local' => 'concurso_empresa_provincia_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('City', array(
             'local' => 'concurso_empresa_ciudad_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));
    }
}