<?php

/**
 * BaseColaboradorEstilos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string             getName() Returns the current record's "name" value
 * @method ColaboradorEstilos setName() Sets the current record's "name" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColaboradorEstilos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colaborador_estilos');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}