<?php

/**
 * BaseUserCompanyCaseStudy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status
 * @property string $user_name
 * @property integer $user_id
 * @property string $name
 * @property integer $road_type_id
 * @property string $direccion
 * @property string $numero
 * @property string $piso
 * @property string $puerta
 * @property integer $states_id
 * @property integer $city_id
 * @property integer $empresa_sector_uno_id
 * @property integer $empresa_sector_dos_id
 * @property integer $empresa_sector_tres_id
 * @property varchar $description
 * @property varchar $summary
 * @property varchar $file1
 * @property varchar $file2
 * @property varchar $file3
 * @property varchar $file4
 * @property varchar $logo
 * @property sfGuardUser $User
 * @property States $States
 * @property City $Localidad
 * @property RoadType $RoadType
 * @property EmpresaSectorUno $EmpresaSectorUno
 * @property EmpresaSectorDos $EmpresaSectorDos
 * @property EmpresaSectorTres $EmpresaSectorTres
 * 
 * @method integer              getStatus()                 Returns the current record's "status" value
 * @method string               getUserName()               Returns the current record's "user_name" value
 * @method integer              getUserId()                 Returns the current record's "user_id" value
 * @method string               getName()                   Returns the current record's "name" value
 * @method integer              getRoadTypeId()             Returns the current record's "road_type_id" value
 * @method string               getDireccion()              Returns the current record's "direccion" value
 * @method string               getNumero()                 Returns the current record's "numero" value
 * @method string               getPiso()                   Returns the current record's "piso" value
 * @method string               getPuerta()                 Returns the current record's "puerta" value
 * @method integer              getStatesId()               Returns the current record's "states_id" value
 * @method integer              getCityId()                 Returns the current record's "city_id" value
 * @method integer              getEmpresaSectorUnoId()     Returns the current record's "empresa_sector_uno_id" value
 * @method integer              getEmpresaSectorDosId()     Returns the current record's "empresa_sector_dos_id" value
 * @method integer              getEmpresaSectorTresId()    Returns the current record's "empresa_sector_tres_id" value
 * @method varchar              getDescription()            Returns the current record's "description" value
 * @method varchar              getSummary()                Returns the current record's "summary" value
 * @method varchar              getFile1()                  Returns the current record's "file1" value
 * @method varchar              getFile2()                  Returns the current record's "file2" value
 * @method varchar              getFile3()                  Returns the current record's "file3" value
 * @method varchar              getFile4()                  Returns the current record's "file4" value
 * @method varchar              getLogo()                   Returns the current record's "logo" value
 * @method sfGuardUser          getUser()                   Returns the current record's "User" value
 * @method States               getStates()                 Returns the current record's "States" value
 * @method City                 getLocalidad()              Returns the current record's "Localidad" value
 * @method RoadType             getRoadType()               Returns the current record's "RoadType" value
 * @method EmpresaSectorUno     getEmpresaSectorUno()       Returns the current record's "EmpresaSectorUno" value
 * @method EmpresaSectorDos     getEmpresaSectorDos()       Returns the current record's "EmpresaSectorDos" value
 * @method EmpresaSectorTres    getEmpresaSectorTres()      Returns the current record's "EmpresaSectorTres" value
 * @method UserCompanyCaseStudy setStatus()                 Sets the current record's "status" value
 * @method UserCompanyCaseStudy setUserName()               Sets the current record's "user_name" value
 * @method UserCompanyCaseStudy setUserId()                 Sets the current record's "user_id" value
 * @method UserCompanyCaseStudy setName()                   Sets the current record's "name" value
 * @method UserCompanyCaseStudy setRoadTypeId()             Sets the current record's "road_type_id" value
 * @method UserCompanyCaseStudy setDireccion()              Sets the current record's "direccion" value
 * @method UserCompanyCaseStudy setNumero()                 Sets the current record's "numero" value
 * @method UserCompanyCaseStudy setPiso()                   Sets the current record's "piso" value
 * @method UserCompanyCaseStudy setPuerta()                 Sets the current record's "puerta" value
 * @method UserCompanyCaseStudy setStatesId()               Sets the current record's "states_id" value
 * @method UserCompanyCaseStudy setCityId()                 Sets the current record's "city_id" value
 * @method UserCompanyCaseStudy setEmpresaSectorUnoId()     Sets the current record's "empresa_sector_uno_id" value
 * @method UserCompanyCaseStudy setEmpresaSectorDosId()     Sets the current record's "empresa_sector_dos_id" value
 * @method UserCompanyCaseStudy setEmpresaSectorTresId()    Sets the current record's "empresa_sector_tres_id" value
 * @method UserCompanyCaseStudy setDescription()            Sets the current record's "description" value
 * @method UserCompanyCaseStudy setSummary()                Sets the current record's "summary" value
 * @method UserCompanyCaseStudy setFile1()                  Sets the current record's "file1" value
 * @method UserCompanyCaseStudy setFile2()                  Sets the current record's "file2" value
 * @method UserCompanyCaseStudy setFile3()                  Sets the current record's "file3" value
 * @method UserCompanyCaseStudy setFile4()                  Sets the current record's "file4" value
 * @method UserCompanyCaseStudy setLogo()                   Sets the current record's "logo" value
 * @method UserCompanyCaseStudy setUser()                   Sets the current record's "User" value
 * @method UserCompanyCaseStudy setStates()                 Sets the current record's "States" value
 * @method UserCompanyCaseStudy setLocalidad()              Sets the current record's "Localidad" value
 * @method UserCompanyCaseStudy setRoadType()               Sets the current record's "RoadType" value
 * @method UserCompanyCaseStudy setEmpresaSectorUno()       Sets the current record's "EmpresaSectorUno" value
 * @method UserCompanyCaseStudy setEmpresaSectorDos()       Sets the current record's "EmpresaSectorDos" value
 * @method UserCompanyCaseStudy setEmpresaSectorTres()      Sets the current record's "EmpresaSectorTres" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserCompanyCaseStudy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_company_case_study');
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'default' => 1,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('user_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('user_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('name', 'string', 70, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('road_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('direccion', 'string', 70, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 70,
             ));
        $this->hasColumn('numero', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('piso', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('puerta', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('states_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_sector_uno_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_sector_dos_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_sector_tres_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('description', 'varchar', 43000, array(
             'type' => 'varchar',
             'length' => 43000,
             ));
        $this->hasColumn('summary', 'varchar', 8300, array(
             'type' => 'varchar',
             'length' => 8300,
             ));
        $this->hasColumn('file1', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file2', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file3', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('file4', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('logo', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('States', array(
             'local' => 'states_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('City as Localidad', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('RoadType', array(
             'local' => 'road_type_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorUno', array(
             'local' => 'empresa_sector_uno_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorDos', array(
             'local' => 'empresa_sector_dos_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('EmpresaSectorTres', array(
             'local' => 'empresa_sector_tres_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}