<?php

/**
 * BasePdActivaDesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $PdCarta
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getPdCarta() Returns the current record's "PdCarta" collection
 * @method PdActivaDesa        setName()    Sets the current record's "name" value
 * @method PdActivaDesa        setPdCarta() Sets the current record's "PdCarta" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePdActivaDesa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pd_activa_desa');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PdCarta', array(
             'local' => 'id',
             'foreign' => 'pd_activa_desa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}