<?php

/**
 * BaseGiftRedemption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property varchar $surname1
 * @property varchar $surname2
 * @property varchar $road_type
 * @property varchar $address
 * @property varchar $number
 * @property varchar $floor
 * @property varchar $door
 * @property integer $states_id
 * @property integer $city_id
 * @property varchar $cp
 * @property varchar $contact_number
 * @property integer $delivery_time
 * @property integer $gift
 * @property integer $user
 * @property integer $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Gift $Gift
 * @property sfGuardUser $sfGuardUser
 * @property States $States
 * @property City $City
 * 
 * @method varchar        getName()           Returns the current record's "name" value
 * @method varchar        getSurname1()       Returns the current record's "surname1" value
 * @method varchar        getSurname2()       Returns the current record's "surname2" value
 * @method varchar        getRoadType()       Returns the current record's "road_type" value
 * @method varchar        getAddress()        Returns the current record's "address" value
 * @method varchar        getNumber()         Returns the current record's "number" value
 * @method varchar        getFloor()          Returns the current record's "floor" value
 * @method varchar        getDoor()           Returns the current record's "door" value
 * @method integer        getStatesId()       Returns the current record's "states_id" value
 * @method integer        getCityId()         Returns the current record's "city_id" value
 * @method varchar        getCp()             Returns the current record's "cp" value
 * @method varchar        getContactNumber()  Returns the current record's "contact_number" value
 * @method integer        getDeliveryTime()   Returns the current record's "delivery_time" value
 * @method integer        getGift()           Returns the current record's "gift" value
 * @method integer        getUser()           Returns the current record's "user" value
 * @method integer        getStatus()         Returns the current record's "status" value
 * @method timestamp      getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()      Returns the current record's "updated_at" value
 * @method Gift           getGift()           Returns the current record's "Gift" value
 * @method sfGuardUser    getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method States         getStates()         Returns the current record's "States" value
 * @method City           getCity()           Returns the current record's "City" value
 * @method GiftRedemption setName()           Sets the current record's "name" value
 * @method GiftRedemption setSurname1()       Sets the current record's "surname1" value
 * @method GiftRedemption setSurname2()       Sets the current record's "surname2" value
 * @method GiftRedemption setRoadType()       Sets the current record's "road_type" value
 * @method GiftRedemption setAddress()        Sets the current record's "address" value
 * @method GiftRedemption setNumber()         Sets the current record's "number" value
 * @method GiftRedemption setFloor()          Sets the current record's "floor" value
 * @method GiftRedemption setDoor()           Sets the current record's "door" value
 * @method GiftRedemption setStatesId()       Sets the current record's "states_id" value
 * @method GiftRedemption setCityId()         Sets the current record's "city_id" value
 * @method GiftRedemption setCp()             Sets the current record's "cp" value
 * @method GiftRedemption setContactNumber()  Sets the current record's "contact_number" value
 * @method GiftRedemption setDeliveryTime()   Sets the current record's "delivery_time" value
 * @method GiftRedemption setGift()           Sets the current record's "gift" value
 * @method GiftRedemption setUser()           Sets the current record's "user" value
 * @method GiftRedemption setStatus()         Sets the current record's "status" value
 * @method GiftRedemption setCreatedAt()      Sets the current record's "created_at" value
 * @method GiftRedemption setUpdatedAt()      Sets the current record's "updated_at" value
 * @method GiftRedemption setGift()           Sets the current record's "Gift" value
 * @method GiftRedemption setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * @method GiftRedemption setStates()         Sets the current record's "States" value
 * @method GiftRedemption setCity()           Sets the current record's "City" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGiftRedemption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gift_redemption');
        $this->hasColumn('name', 'varchar', 32, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 32,
             ));
        $this->hasColumn('surname1', 'varchar', 32, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 32,
             ));
        $this->hasColumn('surname2', 'varchar', 32, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 32,
             ));
        $this->hasColumn('road_type', 'varchar', 32, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('address', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('number', 'varchar', 6, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 6,
             ));
        $this->hasColumn('floor', 'varchar', 4, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('door', 'varchar', 6, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 6,
             ));
        $this->hasColumn('states_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('city_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 7,
             ));
        $this->hasColumn('cp', 'varchar', 5, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('contact_number', 'varchar', 9, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 9,
             ));
        $this->hasColumn('delivery_time', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 7,
             ));
        $this->hasColumn('gift', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('user', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             'length' => 2,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gift', array(
             'local' => 'gift',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('States', array(
             'local' => 'states_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}