<?php

/**
 * BaseConcursoRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $concurso_id
 * @property date $fecha_inicio
 * @property date $fecha_fin
 * 
 * @method integer          getConcursoId()   Returns the current record's "concurso_id" value
 * @method date             getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method date             getFechaFin()     Returns the current record's "fecha_fin" value
 * @method ConcursoRevision setConcursoId()   Sets the current record's "concurso_id" value
 * @method ConcursoRevision setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method ConcursoRevision setFechaFin()     Sets the current record's "fecha_fin" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcursoRevision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concurso_revision');
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_fin', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}