<?php

/**
 * BasePdCarta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $plan_accion
 * @property integer $pd_estado_carta_id
 * @property integer $pd_activa_desa_id
 * @property integer $pd_apro_despro_id
 * @property integer $pd_id
 * @property PdEstadoCarta $PdEstadoCarta
 * @property PdActivaDesa $PdActivaDesa
 * @property PdAproDespro $PdAproDespro
 * @property Pd $Pd
 * 
 * @method string        getName()               Returns the current record's "name" value
 * @method string        getDescription()        Returns the current record's "description" value
 * @method string        getPlanAccion()         Returns the current record's "plan_accion" value
 * @method integer       getPdEstadoCartaId()    Returns the current record's "pd_estado_carta_id" value
 * @method integer       getPdActivaDesaId()     Returns the current record's "pd_activa_desa_id" value
 * @method integer       getPdAproDesproId()     Returns the current record's "pd_apro_despro_id" value
 * @method integer       getPdId()               Returns the current record's "pd_id" value
 * @method PdEstadoCarta getPdEstadoCarta()      Returns the current record's "PdEstadoCarta" value
 * @method PdActivaDesa  getPdActivaDesa()       Returns the current record's "PdActivaDesa" value
 * @method PdAproDespro  getPdAproDespro()       Returns the current record's "PdAproDespro" value
 * @method Pd            getPd()                 Returns the current record's "Pd" value
 * @method PdCarta       setName()               Sets the current record's "name" value
 * @method PdCarta       setDescription()        Sets the current record's "description" value
 * @method PdCarta       setPlanAccion()         Sets the current record's "plan_accion" value
 * @method PdCarta       setPdEstadoCartaId()    Sets the current record's "pd_estado_carta_id" value
 * @method PdCarta       setPdActivaDesaId()     Sets the current record's "pd_activa_desa_id" value
 * @method PdCarta       setPdAproDesproId()     Sets the current record's "pd_apro_despro_id" value
 * @method PdCarta       setPdId()               Sets the current record's "pd_id" value
 * @method PdCarta       setPdEstadoCarta()      Sets the current record's "PdEstadoCarta" value
 * @method PdCarta       setPdActivaDesa()       Sets the current record's "PdActivaDesa" value
 * @method PdCarta       setPdAproDespro()       Sets the current record's "PdAproDespro" value
 * @method PdCarta       setPd()                 Sets the current record's "Pd" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePdCarta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pd_carta');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('plan_accion', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('pd_estado_carta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pd_activa_desa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pd_apro_despro_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pd_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PdEstadoCarta', array(
             'local' => 'pd_estado_carta_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('PdActivaDesa', array(
             'local' => 'pd_activa_desa_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('PdAproDespro', array(
             'local' => 'pd_apro_despro_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Pd', array(
             'local' => 'pd_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}