<?php

/**
 * BaseProfesionalDestacadosTemporales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profesional_id
 * @property integer $tipo_tiempo_id
 * @property Profesional $Profesional
 * @property TipoTiempo $TipoTiempo
 * 
 * @method integer                         getProfesionalId()  Returns the current record's "profesional_id" value
 * @method integer                         getTipoTiempoId()   Returns the current record's "tipo_tiempo_id" value
 * @method Profesional                     getProfesional()    Returns the current record's "Profesional" value
 * @method TipoTiempo                      getTipoTiempo()     Returns the current record's "TipoTiempo" value
 * @method ProfesionalDestacadosTemporales setProfesionalId()  Sets the current record's "profesional_id" value
 * @method ProfesionalDestacadosTemporales setTipoTiempoId()   Sets the current record's "tipo_tiempo_id" value
 * @method ProfesionalDestacadosTemporales setProfesional()    Sets the current record's "Profesional" value
 * @method ProfesionalDestacadosTemporales setTipoTiempo()     Sets the current record's "TipoTiempo" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesionalDestacadosTemporales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesional_destacados_temporales');
        $this->hasColumn('profesional_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_tiempo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profesional', array(
             'local' => 'profesional_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('TipoTiempo', array(
             'local' => 'tipo_tiempo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}