<?php

/**
 * BaseCuestionarioValuesTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $code
 * @property Doctrine_Collection $CuestionarioPregunta
 * 
 * @method string                  getType()                 Returns the current record's "type" value
 * @method string                  getCode()                 Returns the current record's "code" value
 * @method Doctrine_Collection     getCuestionarioPregunta() Returns the current record's "CuestionarioPregunta" collection
 * @method CuestionarioValuesTypes setType()                 Sets the current record's "type" value
 * @method CuestionarioValuesTypes setCode()                 Sets the current record's "code" value
 * @method CuestionarioValuesTypes setCuestionarioPregunta() Sets the current record's "CuestionarioPregunta" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuestionarioValuesTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuestionario_values_types');
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CuestionarioPregunta', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}