<?php

/**
 * BaseProductoDestacado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property integer $producto_tipo_dos_id
 * @property integer $producto_tipo_tres_id
 * @property string $name
 * @property string $marca
 * @property integer $rank
 * @property integer $combinado
 * @property Producto $Producto
 * @property ProductoTipoDos $ProductoTipoDos
 * @property ProductoTipoTres $ProductoTipoTres
 * 
 * @method integer           getProductoId()            Returns the current record's "producto_id" value
 * @method integer           getProductoTipoDosId()     Returns the current record's "producto_tipo_dos_id" value
 * @method integer           getProductoTipoTresId()    Returns the current record's "producto_tipo_tres_id" value
 * @method string            getName()                  Returns the current record's "name" value
 * @method string            getMarca()                 Returns the current record's "marca" value
 * @method integer           getRank()                  Returns the current record's "rank" value
 * @method integer           getCombinado()             Returns the current record's "combinado" value
 * @method Producto          getProducto()              Returns the current record's "Producto" value
 * @method ProductoTipoDos   getProductoTipoDos()       Returns the current record's "ProductoTipoDos" value
 * @method ProductoTipoTres  getProductoTipoTres()      Returns the current record's "ProductoTipoTres" value
 * @method ProductoDestacado setProductoId()            Sets the current record's "producto_id" value
 * @method ProductoDestacado setProductoTipoDosId()     Sets the current record's "producto_tipo_dos_id" value
 * @method ProductoDestacado setProductoTipoTresId()    Sets the current record's "producto_tipo_tres_id" value
 * @method ProductoDestacado setName()                  Sets the current record's "name" value
 * @method ProductoDestacado setMarca()                 Sets the current record's "marca" value
 * @method ProductoDestacado setRank()                  Sets the current record's "rank" value
 * @method ProductoDestacado setCombinado()             Sets the current record's "combinado" value
 * @method ProductoDestacado setProducto()              Sets the current record's "Producto" value
 * @method ProductoDestacado setProductoTipoDos()       Sets the current record's "ProductoTipoDos" value
 * @method ProductoDestacado setProductoTipoTres()      Sets the current record's "ProductoTipoTres" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductoDestacado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_destacado');
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_tipo_dos_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_tipo_tres_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('marca', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('combinado', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('ProductoTipoDos', array(
             'local' => 'producto_tipo_dos_id',
             'foreign' => 'id'));

        $this->hasOne('ProductoTipoTres', array(
             'local' => 'producto_tipo_tres_id',
             'foreign' => 'id'));
    }
}