<?php

/**
 * BaseAdministrationEmails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $email
 * @property integer $permission_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $User
 * @property sfGuardPermission $Permission
 * 
 * @method integer              getUserId()        Returns the current record's "user_id" value
 * @method varchar              getEmail()         Returns the current record's "email" value
 * @method integer              getPermissionId()  Returns the current record's "permission_id" value
 * @method timestamp            getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp            getUpdatedAt()     Returns the current record's "updated_at" value
 * @method sfGuardUser          getUser()          Returns the current record's "User" value
 * @method sfGuardPermission    getPermission()    Returns the current record's "Permission" value
 * @method AdministrationEmails setUserId()        Sets the current record's "user_id" value
 * @method AdministrationEmails setEmail()         Sets the current record's "email" value
 * @method AdministrationEmails setPermissionId()  Sets the current record's "permission_id" value
 * @method AdministrationEmails setCreatedAt()     Sets the current record's "created_at" value
 * @method AdministrationEmails setUpdatedAt()     Sets the current record's "updated_at" value
 * @method AdministrationEmails setUser()          Sets the current record's "User" value
 * @method AdministrationEmails setPermission()    Sets the current record's "Permission" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministrationEmails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administration_emails');
        $this->hasColumn('user_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('email', 'varchar', 70, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 70,
             ));
        $this->hasColumn('permission_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 7,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}