<?php

/**
 * BaseColaboradorNivelDos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * @property string $orden
 * @property string $image
 * @property integer $colaborador_nivel_uno_id
 * @property ColaboradorNivelUno $ColaboradorNivelUno
 * @property Doctrine_Collection $sfGuardUserProfile
 * 
 * @method string              getName()                     Returns the current record's "name" value
 * @method string              getValue()                    Returns the current record's "value" value
 * @method string              getOrden()                    Returns the current record's "orden" value
 * @method string              getImage()                    Returns the current record's "image" value
 * @method integer             getColaboradorNivelUnoId()    Returns the current record's "colaborador_nivel_uno_id" value
 * @method ColaboradorNivelUno getColaboradorNivelUno()      Returns the current record's "ColaboradorNivelUno" value
 * @method Doctrine_Collection getSfGuardUserProfile()       Returns the current record's "sfGuardUserProfile" collection
 * @method ColaboradorNivelDos setName()                     Sets the current record's "name" value
 * @method ColaboradorNivelDos setValue()                    Sets the current record's "value" value
 * @method ColaboradorNivelDos setOrden()                    Sets the current record's "orden" value
 * @method ColaboradorNivelDos setImage()                    Sets the current record's "image" value
 * @method ColaboradorNivelDos setColaboradorNivelUnoId()    Sets the current record's "colaborador_nivel_uno_id" value
 * @method ColaboradorNivelDos setColaboradorNivelUno()      Sets the current record's "ColaboradorNivelUno" value
 * @method ColaboradorNivelDos setSfGuardUserProfile()       Sets the current record's "sfGuardUserProfile" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColaboradorNivelDos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('colaborador_nivel_dos');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('value', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('orden', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('colaborador_nivel_uno_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ColaboradorNivelUno', array(
             'local' => 'colaborador_nivel_uno_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'colaborador_nivel_dos_id'));
    }
}