<?php

/**
 * BaseListaCuestionario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $tipo
 * @property integer $empresa_sector_uno_id
 * @property integer $empresa_sector_dos_id
 * @property integer $empresa_sector_tres_id
 * @property integer $producto_tipo_uno_id
 * @property integer $producto_tipo_dos_id
 * @property integer $producto_tipo_tres_id
 * @property EmpresaSectorUno $EmpresaSectorUno
 * @property EmpresaSectorDos $EmpresaSectorDos
 * @property EmpresaSectorTres $EmpresaSectorTres
 * @property ProductoTipoUno $ProductoTipoUno
 * @property ProductoTipoDos $ProductoTipoDos
 * @property ProductoTipoTres $ProductoTipoTres
 * @property Doctrine_Collection $Productos
 * @property Doctrine_Collection $Empresa
 * @property Doctrine_Collection $ListaCuestionarioUser
 * @property Doctrine_Collection $ListaCuestionarioPregunta
 * 
 * @method string              getNombre()                    Returns the current record's "nombre" value
 * @method string              getTipo()                      Returns the current record's "tipo" value
 * @method integer             getEmpresaSectorUnoId()        Returns the current record's "empresa_sector_uno_id" value
 * @method integer             getEmpresaSectorDosId()        Returns the current record's "empresa_sector_dos_id" value
 * @method integer             getEmpresaSectorTresId()       Returns the current record's "empresa_sector_tres_id" value
 * @method integer             getProductoTipoUnoId()         Returns the current record's "producto_tipo_uno_id" value
 * @method integer             getProductoTipoDosId()         Returns the current record's "producto_tipo_dos_id" value
 * @method integer             getProductoTipoTresId()        Returns the current record's "producto_tipo_tres_id" value
 * @method EmpresaSectorUno    getEmpresaSectorUno()          Returns the current record's "EmpresaSectorUno" value
 * @method EmpresaSectorDos    getEmpresaSectorDos()          Returns the current record's "EmpresaSectorDos" value
 * @method EmpresaSectorTres   getEmpresaSectorTres()         Returns the current record's "EmpresaSectorTres" value
 * @method ProductoTipoUno     getProductoTipoUno()           Returns the current record's "ProductoTipoUno" value
 * @method ProductoTipoDos     getProductoTipoDos()           Returns the current record's "ProductoTipoDos" value
 * @method ProductoTipoTres    getProductoTipoTres()          Returns the current record's "ProductoTipoTres" value
 * @method Doctrine_Collection getProductos()                 Returns the current record's "Productos" collection
 * @method Doctrine_Collection getEmpresa()                   Returns the current record's "Empresa" collection
 * @method Doctrine_Collection getListaCuestionarioUser()     Returns the current record's "ListaCuestionarioUser" collection
 * @method Doctrine_Collection getListaCuestionarioPregunta() Returns the current record's "ListaCuestionarioPregunta" collection
 * @method ListaCuestionario   setNombre()                    Sets the current record's "nombre" value
 * @method ListaCuestionario   setTipo()                      Sets the current record's "tipo" value
 * @method ListaCuestionario   setEmpresaSectorUnoId()        Sets the current record's "empresa_sector_uno_id" value
 * @method ListaCuestionario   setEmpresaSectorDosId()        Sets the current record's "empresa_sector_dos_id" value
 * @method ListaCuestionario   setEmpresaSectorTresId()       Sets the current record's "empresa_sector_tres_id" value
 * @method ListaCuestionario   setProductoTipoUnoId()         Sets the current record's "producto_tipo_uno_id" value
 * @method ListaCuestionario   setProductoTipoDosId()         Sets the current record's "producto_tipo_dos_id" value
 * @method ListaCuestionario   setProductoTipoTresId()        Sets the current record's "producto_tipo_tres_id" value
 * @method ListaCuestionario   setEmpresaSectorUno()          Sets the current record's "EmpresaSectorUno" value
 * @method ListaCuestionario   setEmpresaSectorDos()          Sets the current record's "EmpresaSectorDos" value
 * @method ListaCuestionario   setEmpresaSectorTres()         Sets the current record's "EmpresaSectorTres" value
 * @method ListaCuestionario   setProductoTipoUno()           Sets the current record's "ProductoTipoUno" value
 * @method ListaCuestionario   setProductoTipoDos()           Sets the current record's "ProductoTipoDos" value
 * @method ListaCuestionario   setProductoTipoTres()          Sets the current record's "ProductoTipoTres" value
 * @method ListaCuestionario   setProductos()                 Sets the current record's "Productos" collection
 * @method ListaCuestionario   setEmpresa()                   Sets the current record's "Empresa" collection
 * @method ListaCuestionario   setListaCuestionarioUser()     Sets the current record's "ListaCuestionarioUser" collection
 * @method ListaCuestionario   setListaCuestionarioPregunta() Sets the current record's "ListaCuestionarioPregunta" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaCuestionario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_cuestionario');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('empresa_sector_uno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('empresa_sector_dos_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('empresa_sector_tres_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_tipo_uno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_tipo_dos_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_tipo_tres_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EmpresaSectorUno', array(
             'local' => 'empresa_sector_uno_id',
             'foreign' => 'id'));

        $this->hasOne('EmpresaSectorDos', array(
             'local' => 'empresa_sector_dos_id',
             'foreign' => 'id'));

        $this->hasOne('EmpresaSectorTres', array(
             'local' => 'empresa_sector_tres_id',
             'foreign' => 'id'));

        $this->hasOne('ProductoTipoUno', array(
             'local' => 'producto_tipo_uno_id',
             'foreign' => 'id'));

        $this->hasOne('ProductoTipoDos', array(
             'local' => 'producto_tipo_dos_id',
             'foreign' => 'id'));

        $this->hasOne('ProductoTipoTres', array(
             'local' => 'producto_tipo_tres_id',
             'foreign' => 'id'));

        $this->hasMany('Producto as Productos', array(
             'local' => 'id',
             'foreign' => 'lista_cuestionario_id'));

        $this->hasMany('Empresa', array(
             'local' => 'id',
             'foreign' => 'lista_cuestionario_id'));

        $this->hasMany('ListaCuestionarioUser', array(
             'local' => 'id',
             'foreign' => 'lista_cuestionario_id'));

        $this->hasMany('ListaCuestionarioPregunta', array(
             'local' => 'id',
             'foreign' => 'lista_cuestionario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}