<?php

/**
 * BaseInforma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $se_crea_un_concurso_para_producto
 * @property string $se_crea_un_concurso_para_empresa
 * @property string $un_concurso_en_el_que_contribuyes_finaliza_en_3_dias
 * @property string $una_mesa_redonda_en_el_que_contribuyes_finaliza_en_3_dias
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()                                                    Returns the current record's "user_id" value
 * @method string      getSeCreaUnConcursoParaProducto()                              Returns the current record's "se_crea_un_concurso_para_producto" value
 * @method string      getSeCreaUnConcursoParaEmpresa()                               Returns the current record's "se_crea_un_concurso_para_empresa" value
 * @method string      getUnConcursoEnElQueContribuyesFinalizaEn3Dias()               Returns the current record's "un_concurso_en_el_que_contribuyes_finaliza_en_3_dias" value
 * @method string      getUnaMesaRedondaEnElQueContribuyesFinalizaEn3Dias()           Returns the current record's "una_mesa_redonda_en_el_que_contribuyes_finaliza_en_3_dias" value
 * @method sfGuardUser getSfGuardUser()                                               Returns the current record's "sfGuardUser" value
 * @method Informa     setUserId()                                                    Sets the current record's "user_id" value
 * @method Informa     setSeCreaUnConcursoParaProducto()                              Sets the current record's "se_crea_un_concurso_para_producto" value
 * @method Informa     setSeCreaUnConcursoParaEmpresa()                               Sets the current record's "se_crea_un_concurso_para_empresa" value
 * @method Informa     setUnConcursoEnElQueContribuyesFinalizaEn3Dias()               Sets the current record's "un_concurso_en_el_que_contribuyes_finaliza_en_3_dias" value
 * @method Informa     setUnaMesaRedondaEnElQueContribuyesFinalizaEn3Dias()           Sets the current record's "una_mesa_redonda_en_el_que_contribuyes_finaliza_en_3_dias" value
 * @method Informa     setSfGuardUser()                                               Sets the current record's "sfGuardUser" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInforma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('informa');
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('se_crea_un_concurso_para_producto', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('se_crea_un_concurso_para_empresa', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('un_concurso_en_el_que_contribuyes_finaliza_en_3_dias', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('una_mesa_redonda_en_el_que_contribuyes_finaliza_en_3_dias', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}