<?php

/**
 * BaseListaCuestionarioUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $lista_cuestionario_id
 * @property boolean $aprobado
 * @property integer $empresa_id
 * @property integer $producto_id
 * @property boolean $disabled
 * @property sfGuardUser $User
 * @property ListaCuestionario $Cuestionario
 * @property Empresa $Empresa
 * @property Producto $Producto
 * @property Doctrine_Collection $Respuestas
 * 
 * @method integer               getUserId()                Returns the current record's "user_id" value
 * @method integer               getListaCuestionarioId()   Returns the current record's "lista_cuestionario_id" value
 * @method boolean               getAprobado()              Returns the current record's "aprobado" value
 * @method integer               getEmpresaId()             Returns the current record's "empresa_id" value
 * @method integer               getProductoId()            Returns the current record's "producto_id" value
 * @method boolean               getDisabled()              Returns the current record's "disabled" value
 * @method sfGuardUser           getUser()                  Returns the current record's "User" value
 * @method ListaCuestionario     getCuestionario()          Returns the current record's "Cuestionario" value
 * @method Empresa               getEmpresa()               Returns the current record's "Empresa" value
 * @method Producto              getProducto()              Returns the current record's "Producto" value
 * @method Doctrine_Collection   getRespuestas()            Returns the current record's "Respuestas" collection
 * @method ListaCuestionarioUser setUserId()                Sets the current record's "user_id" value
 * @method ListaCuestionarioUser setListaCuestionarioId()   Sets the current record's "lista_cuestionario_id" value
 * @method ListaCuestionarioUser setAprobado()              Sets the current record's "aprobado" value
 * @method ListaCuestionarioUser setEmpresaId()             Sets the current record's "empresa_id" value
 * @method ListaCuestionarioUser setProductoId()            Sets the current record's "producto_id" value
 * @method ListaCuestionarioUser setDisabled()              Sets the current record's "disabled" value
 * @method ListaCuestionarioUser setUser()                  Sets the current record's "User" value
 * @method ListaCuestionarioUser setCuestionario()          Sets the current record's "Cuestionario" value
 * @method ListaCuestionarioUser setEmpresa()               Sets the current record's "Empresa" value
 * @method ListaCuestionarioUser setProducto()              Sets the current record's "Producto" value
 * @method ListaCuestionarioUser setRespuestas()            Sets the current record's "Respuestas" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaCuestionarioUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_cuestionario_user');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lista_cuestionario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('aprobado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ListaCuestionario as Cuestionario', array(
             'local' => 'lista_cuestionario_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasMany('ListaCuestionarioRespuesta as Respuestas', array(
             'local' => 'id',
             'foreign' => 'lista_cuestionario_user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}