<?php

/**
 * BaseCuestionarioPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property integer $type_id
 * @property CuestionarioValuesTypes $CuestionarioValuesTypes
 * @property Doctrine_Collection $CuestionarioBajaValue
 * 
 * @method string                  getLabel()                   Returns the current record's "label" value
 * @method integer                 getTypeId()                  Returns the current record's "type_id" value
 * @method CuestionarioValuesTypes getCuestionarioValuesTypes() Returns the current record's "CuestionarioValuesTypes" value
 * @method Doctrine_Collection     getCuestionarioBajaValue()   Returns the current record's "CuestionarioBajaValue" collection
 * @method CuestionarioPregunta    setLabel()                   Sets the current record's "label" value
 * @method CuestionarioPregunta    setTypeId()                  Sets the current record's "type_id" value
 * @method CuestionarioPregunta    setCuestionarioValuesTypes() Sets the current record's "CuestionarioValuesTypes" value
 * @method CuestionarioPregunta    setCuestionarioBajaValue()   Sets the current record's "CuestionarioBajaValue" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuestionarioPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuestionario_pregunta');
        $this->hasColumn('label', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CuestionarioValuesTypes', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('CuestionarioBajaValue', array(
             'local' => 'id',
             'foreign' => 'pregunta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}