<?php

/**
 * BaseTipoDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $MetodoPaypal
 * @property Doctrine_Collection $MetodoBanco
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getMetodoPaypal() Returns the current record's "MetodoPaypal" collection
 * @method Doctrine_Collection getMetodoBanco()  Returns the current record's "MetodoBanco" collection
 * @method TipoDocumento       setName()         Sets the current record's "name" value
 * @method TipoDocumento       setMetodoPaypal() Sets the current record's "MetodoPaypal" collection
 * @method TipoDocumento       setMetodoBanco()  Sets the current record's "MetodoBanco" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_documento');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MetodoPaypal', array(
             'local' => 'id',
             'foreign' => 'tipo_documento_id'));

        $this->hasMany('MetodoBanco', array(
             'local' => 'id',
             'foreign' => 'tipo_documento_id'));
    }
}