<?php

/**
 * BaseCategoriaExcelencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $valor_min
 * @property integer $valor_max
 * 
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method integer             getValorMin()  Returns the current record's "valor_min" value
 * @method integer             getValorMax()  Returns the current record's "valor_max" value
 * @method CategoriaExcelencia setNombre()    Sets the current record's "nombre" value
 * @method CategoriaExcelencia setValorMin()  Sets the current record's "valor_min" value
 * @method CategoriaExcelencia setValorMax()  Sets the current record's "valor_max" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriaExcelencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_excelencia');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('valor_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('valor_max', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}