<?php

/**
 * BaseJerarquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $points
 * @property Doctrine_Collection $RewardLog
 * @property Doctrine_Collection $Gift
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getPoints()    Returns the current record's "points" value
 * @method Doctrine_Collection getRewardLog() Returns the current record's "RewardLog" collection
 * @method Doctrine_Collection getGift()      Returns the current record's "Gift" collection
 * @method Jerarquia           setName()      Sets the current record's "name" value
 * @method Jerarquia           setPoints()    Sets the current record's "points" value
 * @method Jerarquia           setRewardLog() Sets the current record's "RewardLog" collection
 * @method Jerarquia           setGift()      Sets the current record's "Gift" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJerarquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jerarquia');
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('points', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RewardLog', array(
             'local' => 'id',
             'foreign' => 'hierarchy'));

        $this->hasMany('Gift', array(
             'local' => 'id',
             'foreign' => 'hierarchy'));
    }
}