<?php

/**
 * BaseKpi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $tipo
 * @property Doctrine_Collection $KpiProfesionales
 * @property Doctrine_Collection $ListaCuestionarioPregunta
 * @property Doctrine_Collection $KpiEmpresaProducto
 * 
 * @method string              getNombre()                    Returns the current record's "nombre" value
 * @method string              getTipo()                      Returns the current record's "tipo" value
 * @method Doctrine_Collection getKpiProfesionales()          Returns the current record's "KpiProfesionales" collection
 * @method Doctrine_Collection getListaCuestionarioPregunta() Returns the current record's "ListaCuestionarioPregunta" collection
 * @method Doctrine_Collection getKpiEmpresaProducto()        Returns the current record's "KpiEmpresaProducto" collection
 * @method Kpi                 setNombre()                    Sets the current record's "nombre" value
 * @method Kpi                 setTipo()                      Sets the current record's "tipo" value
 * @method Kpi                 setKpiProfesionales()          Sets the current record's "KpiProfesionales" collection
 * @method Kpi                 setListaCuestionarioPregunta() Sets the current record's "ListaCuestionarioPregunta" collection
 * @method Kpi                 setKpiEmpresaProducto()        Sets the current record's "KpiEmpresaProducto" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKpi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kpi');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));


        $this->index('tipo_index', array(
             'fields' => 
             array(
              0 => 'tipo',
             ),
             ));
        $this->index('nombre_index', array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('KpiProfesionales', array(
             'local' => 'id',
             'foreign' => 'kpi_id'));

        $this->hasMany('ListaCuestionarioPregunta', array(
             'local' => 'id',
             'foreign' => 'kpi_id'));

        $this->hasMany('KpiEmpresaProducto', array(
             'local' => 'id',
             'foreign' => 'kpi_id'));
    }
}