<?php

/**
 * BaseMesaredondaCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image
 * @property Doctrine_Collection $MesaRedonda
 * 
 * @method string               getName()        Returns the current record's "name" value
 * @method string               getImage()       Returns the current record's "image" value
 * @method Doctrine_Collection  getMesaRedonda() Returns the current record's "MesaRedonda" collection
 * @method MesaredondaCategoria setName()        Sets the current record's "name" value
 * @method MesaredondaCategoria setImage()       Sets the current record's "image" value
 * @method MesaredondaCategoria setMesaRedonda() Sets the current record's "MesaRedonda" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMesaredondaCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mesaredonda_categoria');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MesaRedonda', array(
             'local' => 'id',
             'foreign' => 'mesaredonda_categoria_id'));
    }
}