<?php

/**
 * BaseOrderPreferences
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $key_id
 * @property longtext $orden
 * @property sfGuardUser $User
 * 
 * @method integer          getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string           getKeyId()            Returns the current record's "key_id" value
 * @method longtext         getOrden()            Returns the current record's "orden" value
 * @method sfGuardUser      getUser()             Returns the current record's "User" value
 * @method OrderPreferences setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method OrderPreferences setKeyId()            Sets the current record's "key_id" value
 * @method OrderPreferences setOrden()            Sets the current record's "orden" value
 * @method OrderPreferences setUser()             Sets the current record's "User" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderPreferences extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_preferences');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('key_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('orden', 'longtext', null, array(
             'type' => 'longtext',
             ));


        $this->index('idx_key', array(
             'fields' => 
             array(
              0 => 'key_id',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));
    }
}