<?php

/**
 * BaseProfesionalGoogleMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $address
 * @property decimal $lat
 * @property decimal $lng
 * @property integer $zoom
 * @property decimal $marker_lat
 * @property decimal $marker_lng
 * @property integer $profesional_id
 * @property Profesional $Profesional
 * 
 * @method string               getAddress()        Returns the current record's "address" value
 * @method decimal              getLat()            Returns the current record's "lat" value
 * @method decimal              getLng()            Returns the current record's "lng" value
 * @method integer              getZoom()           Returns the current record's "zoom" value
 * @method decimal              getMarkerLat()      Returns the current record's "marker_lat" value
 * @method decimal              getMarkerLng()      Returns the current record's "marker_lng" value
 * @method integer              getProfesionalId()  Returns the current record's "profesional_id" value
 * @method Profesional          getProfesional()    Returns the current record's "Profesional" value
 * @method ProfesionalGoogleMap setAddress()        Sets the current record's "address" value
 * @method ProfesionalGoogleMap setLat()            Sets the current record's "lat" value
 * @method ProfesionalGoogleMap setLng()            Sets the current record's "lng" value
 * @method ProfesionalGoogleMap setZoom()           Sets the current record's "zoom" value
 * @method ProfesionalGoogleMap setMarkerLat()      Sets the current record's "marker_lat" value
 * @method ProfesionalGoogleMap setMarkerLng()      Sets the current record's "marker_lng" value
 * @method ProfesionalGoogleMap setProfesionalId()  Sets the current record's "profesional_id" value
 * @method ProfesionalGoogleMap setProfesional()    Sets the current record's "Profesional" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesionalGoogleMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesional_google_map');
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('lng', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('zoom', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('marker_lat', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('marker_lng', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('profesional_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profesional', array(
             'local' => 'profesional_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}