<?php

/**
 * BaseProfesionalLetterArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profesional_letter_id
 * @property string $file
 * @property ProfesionalLetter $ProfesionalLetter
 * 
 * @method integer                  getProfesionalLetterId()   Returns the current record's "profesional_letter_id" value
 * @method string                   getFile()                  Returns the current record's "file" value
 * @method ProfesionalLetter        getProfesionalLetter()     Returns the current record's "ProfesionalLetter" value
 * @method ProfesionalLetterArchivo setProfesionalLetterId()   Sets the current record's "profesional_letter_id" value
 * @method ProfesionalLetterArchivo setFile()                  Sets the current record's "file" value
 * @method ProfesionalLetterArchivo setProfesionalLetter()     Sets the current record's "ProfesionalLetter" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesionalLetterArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesional_letter_archivo');
        $this->hasColumn('profesional_letter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProfesionalLetter', array(
             'local' => 'profesional_letter_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}