<?php

/**
 * BasePizarra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $text
 * @property varchar $seccion
 * @property text $visibilidad
 * @property integer $velocidad
 * @property timestamp $desde
 * @property timestamp $hasta
 * @property varchar $days
 * @property varchar $months
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $PizarraSectionMapping
 * 
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getText()                  Returns the current record's "text" value
 * @method varchar             getSeccion()               Returns the current record's "seccion" value
 * @method text                getVisibilidad()           Returns the current record's "visibilidad" value
 * @method integer             getVelocidad()             Returns the current record's "velocidad" value
 * @method timestamp           getDesde()                 Returns the current record's "desde" value
 * @method timestamp           getHasta()                 Returns the current record's "hasta" value
 * @method varchar             getDays()                  Returns the current record's "days" value
 * @method varchar             getMonths()                Returns the current record's "months" value
 * @method timestamp           getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()             Returns the current record's "updated_at" value
 * @method Doctrine_Collection getPizarraSectionMapping() Returns the current record's "PizarraSectionMapping" collection
 * @method Pizarra             setName()                  Sets the current record's "name" value
 * @method Pizarra             setText()                  Sets the current record's "text" value
 * @method Pizarra             setSeccion()               Sets the current record's "seccion" value
 * @method Pizarra             setVisibilidad()           Sets the current record's "visibilidad" value
 * @method Pizarra             setVelocidad()             Sets the current record's "velocidad" value
 * @method Pizarra             setDesde()                 Sets the current record's "desde" value
 * @method Pizarra             setHasta()                 Sets the current record's "hasta" value
 * @method Pizarra             setDays()                  Sets the current record's "days" value
 * @method Pizarra             setMonths()                Sets the current record's "months" value
 * @method Pizarra             setCreatedAt()             Sets the current record's "created_at" value
 * @method Pizarra             setUpdatedAt()             Sets the current record's "updated_at" value
 * @method Pizarra             setPizarraSectionMapping() Sets the current record's "PizarraSectionMapping" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePizarra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pizarra');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('text', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('seccion', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('visibilidad', 'text', 16, array(
             'type' => 'text',
             'notnull' => true,
             'length' => 16,
             ));
        $this->hasColumn('velocidad', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('desde', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('hasta', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('days', 'varchar', 30, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('months', 'varchar', 30, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PizarraSectionMapping', array(
             'local' => 'id',
             'foreign' => 'pizarra_id'));
    }
}