<?php

/**
 * BaseConcursoReferendumCp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $concurso_cp_id
 * @property integer $contribucion_cp_id
 * @property integer $value
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * @property ContribucionCp $ContribucionCp
 * @property ConcursoCp $ConcursoCp
 * 
 * @method integer              getConcursoCpId()       Returns the current record's "concurso_cp_id" value
 * @method integer              getContribucionCpId()   Returns the current record's "contribucion_cp_id" value
 * @method integer              getValue()              Returns the current record's "value" value
 * @method integer              getUserId()             Returns the current record's "user_id" value
 * @method sfGuardUser          getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method ContribucionCp       getContribucionCp()     Returns the current record's "ContribucionCp" value
 * @method ConcursoCp           getConcursoCp()         Returns the current record's "ConcursoCp" value
 * @method ConcursoReferendumCp setConcursoCpId()       Sets the current record's "concurso_cp_id" value
 * @method ConcursoReferendumCp setContribucionCpId()   Sets the current record's "contribucion_cp_id" value
 * @method ConcursoReferendumCp setValue()              Sets the current record's "value" value
 * @method ConcursoReferendumCp setUserId()             Sets the current record's "user_id" value
 * @method ConcursoReferendumCp setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method ConcursoReferendumCp setContribucionCp()     Sets the current record's "ContribucionCp" value
 * @method ConcursoReferendumCp setConcursoCp()         Sets the current record's "ConcursoCp" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcursoReferendumCp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concurso_referendum_cp');
        $this->hasColumn('concurso_cp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contribucion_cp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ContribucionCp', array(
             'local' => 'contribucion_cp_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ConcursoCp', array(
             'local' => 'concurso_cp_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}