<?php

/**
 * BaseAuditanos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status
 * @property string $usuario
 * @property integer $user_id
 * @property string $email
 * @property string $phone
 * @property string $plan
 * @property string $fichero1
 * @property string $fichero2
 * @property string $fichero3
 * @property string $fichero4
 * @property string $fichero5
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getStatus()      Returns the current record's "status" value
 * @method string      getUsuario()     Returns the current record's "usuario" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getEmail()       Returns the current record's "email" value
 * @method string      getPhone()       Returns the current record's "phone" value
 * @method string      getPlan()        Returns the current record's "plan" value
 * @method string      getFichero1()    Returns the current record's "fichero1" value
 * @method string      getFichero2()    Returns the current record's "fichero2" value
 * @method string      getFichero3()    Returns the current record's "fichero3" value
 * @method string      getFichero4()    Returns the current record's "fichero4" value
 * @method string      getFichero5()    Returns the current record's "fichero5" value
 * @method timestamp   getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()   Returns the current record's "updated_at" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Auditanos   setStatus()      Sets the current record's "status" value
 * @method Auditanos   setUsuario()     Sets the current record's "usuario" value
 * @method Auditanos   setUserId()      Sets the current record's "user_id" value
 * @method Auditanos   setEmail()       Sets the current record's "email" value
 * @method Auditanos   setPhone()       Sets the current record's "phone" value
 * @method Auditanos   setPlan()        Sets the current record's "plan" value
 * @method Auditanos   setFichero1()    Sets the current record's "fichero1" value
 * @method Auditanos   setFichero2()    Sets the current record's "fichero2" value
 * @method Auditanos   setFichero3()    Sets the current record's "fichero3" value
 * @method Auditanos   setFichero4()    Sets the current record's "fichero4" value
 * @method Auditanos   setFichero5()    Sets the current record's "fichero5" value
 * @method Auditanos   setCreatedAt()   Sets the current record's "created_at" value
 * @method Auditanos   setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Auditanos   setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuditanos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auditanos');
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 5,
             ));
        $this->hasColumn('usuario', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('plan', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('fichero1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fichero2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fichero3', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fichero4', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fichero5', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));
    }
}