# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Auditoscopia Admin panel
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/sfDoctrinePlugin/css/default.css, backend_style.css, forms_backend.css, ui-lightness/jquery-ui-1.8.18.custom.css, jquery.autocomplete.css]
  javascripts:    [jquery-1.7.2.min.js, jquery-ui-1.8.6.custom.min.js, /js/ckeditor/ckeditor.js, jquery.autocomplete.admin.js, general.js]

  has_layout:     true
  layout:         layout
