generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserCompanyCaseStudy
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_company_case_study
    with_doctrine_route:   true
    actions_base_class:    sfActions

    css: nothing

    config:
      actions:
         _new: { label: "Nuevo caso de éxito"}
      fields:
        divisor: { label: Auditorías}
        factor_formula: { label: Factor de fórmula }
        name: { label: Empresa/Entidad }
        states_id : { label: Provincia, sortBy : s.states_id }
        sector: { label: Actividad }
        dividendo: { label: Puntos totales}
        divisor: { label: Auditorías realizadas }
        isDestacada: { label: Destacada }
        road_type_id : { label: Tipo de vía }
        numero : { label: Nº }
        city_id : { label: Localidad, sortBy : c.city_id }
        sectorName : { label: Sector, sortBy : esu.sectorName }
        subSectorName : { label: Subsector, sortBy : esd.subSectorName }
        sector : { label: Actividad, sortBy : esd.sector }
        created_at: { label: Creado el }
        description: { label: Descripción del caso de éxito }
        summary: { label: Resumen del caso de éxito }
        user_name: { label: Usuario }

      list:
        max_per_page: 25
        title: Listado de otros casos de éxito de Empresa/Entidad
        display: [ _created_at, name, states_id , city_id,sectorName, subSectorName, sector  , user_name, _status]
        table_method: doSelectJoinSectors
        object_actions:
          _ver: { label: ver, action: show }
          _edit: ~
          _delete: ~
          _processed: { label: Tramitado, action: processed}
          _closed: { label: Cerrado , action: closed}
      filter:
        display: [created_at,name,states_id,city_id,empresa_sector_uno_id,empresa_sector_dos_id,empresa_sector_tres_id,user_name,status]
      form:
        actions:
          _delete: ~
          _list: ~
          _save: ~
          _save_and_add: { label: Guardar y crear otro }
      edit:
        title: Editar otro caso de éxito de Empresa/Entidad
      new:
        title: Nuevo otro caso de éxito de Empresa/Entidad
