generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Profesional
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profesional_lista
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions:
         _new: { label: "Nuevo profesional"}
      fields:
        created_at: { label: Creado el, date_format: dd/MM/y }
        first_name: { label: Nombre }
        last_name_one: { label: Apellido 1 }
        last_name_two: { label: Apellido 2 }
        profesional_estado: { label: Estado }
        tipo_tres : { label: Actividad, is_real: true}
        States: { label: Provincia, is_real: true }
        City: { label: Localidad, is_real: true }
        city_id: { label: Localidad }
        user_id:  { label: Usuario }
        username:  { label: Usuario, is_real: true }
        profesional_tipo_uno_id: { label: Sector }
        profesional_tipo_uno: { label: Sector, is_real: true }
        profesional_tipo_dos_id: { label: Subsector }
        profesional_tipo_dos: { label: Subsector, is_real: true } 
        isDestacada: { label: Destacada }
        featured: { label: Home }
        featured_order: { label: Orden Home   }
      list:
        table_method: getListaQuery
        max_per_page: 25
        title: Listado de profesionales
        display: [ created_at, last_name_one, last_name_two, first_name, States, City, profesional_tipo_uno,profesional_tipo_dos, tipo_tres, username, profesional_estado ,_isDestacada, _featured, featured_order]
        table_method: doSelectJoinForListing
        object_actions:
          _show: { label: Ver, action: show }
          featured:
            action: setFeatured
            label: Home
          featured_order:
            action: setFeaturedOrder
            label: Orden Home
          _edit: ~
          _delete: ~         
          destacar: { label: Destacar, action: destacadoManager }
      filter:
        fields:
          profesional_estado: { label: Profesional estado }
        display: [ created_at, last_name_one, last_name_two, first_name, states_id, city_id , profesional_tipo_uno_id, profesional_tipo_dos_id, profesional_tipo_tres_id, user_id, profesional_estado ]
      form:
        actions:
          _delete: ~
          _list: ~
          _save: ~
      edit:
        title: Editar un profesional

      new:
        title: Nuevo profesional
