generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CompanyCaseStudy
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          company_case_study
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css: nothing

    config:
      actions:
         _new: { label: "Nuevo caso de éxito"}
      fields:
        divisor: { label: Auditorías}
        factor_formula: { label: Factor de fórmula }
        name: { label: Empresa/Entidad }
        states_id : { label: Provincia}
        Statesname : { label: Provincia, sortBy : s.Statesname }
        sector: { label: Actividad }
        dividendo: { label: Puntos totales}
        divisor: { label: Auditorías realizadas }
        isDestacada: { label: Destacada }
        road_type_id : { label: Tipo de vía }
        numero : { label: Nº }
        city_id : { label: Localidad }
        CityName: { label: Localidad, sortBy : c.CityName }
        SectorName : { label: Sector, sortBy : esu.name }
        SubSectorName : { label: Subsector, sortBy : esd.name }
        ActividadName : { label: Actividad, sortBy : est.namesssss }
        created_at: { label: Creado el }
        description: { label: Descripción del caso de éxito }
        summary: { label: Resumen del caso de éxito }
        
      list:
        max_per_page: 25
        title: Listado de nuestros casos de éxito de Empresa/Entidad 
        display: [ _created_at, name, Statesname, CityName, SectorName, SubSectorName, ActividadName  , _status]
        table_method: doSelectJoinSector
        object_actions:
          _ver: { label: ver, action: show }
          _edit: ~
          _delete: ~
          _processed: { label: Tramitado, action: processed}
          _closed: { label: Cerrado , action: closed}
      filter:
        display: [ created_at, name, states_id , city_id, empresa_sector_uno_id, empresa_sector_dos_id, empresa_sector_tres_id  , status]
      form:
        
      edit:    
        title: Editar caso de éxito de Empresa/Entidad 
      new:
        title: Nuevo caso de éxito de Empresa/Entidad
        
        
