# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:  [main.css,global.css,estyl_side.css,estyl_sup.css,user.css]

  javascripts:    [jquery-1.7.2.min.js, jquery-ui-1.8.6.custom.min.js,jquery.autocompleter.js,/sfDependentSelectPlugin/js/SelectDependiente.min.js,/sfJQueryUIPlugin/js/i18n/ui.datepicker-es.js,close_flash.js]

  has_layout:     true
  layout:         layout_home
