generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contribucion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contribucion_planes_de_accion
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                    nothing

    config:
      fields:      
        name: { label: Contribución }
        resume_name: { label: Contribución }
        concurso: { label: Concurso }
        resume_concurso: { label: Concurso , sortBy : c.name }
        concurso_created_at: { label: Creado el }
        concurso_estado: { label: Estado concurso }
        contribucion_estado: { label: Estado contribucion }
        concurso_categoria: { label: Categoría }
        concurso_empresa: { label: Empresa/Entidad }
        concurso_actividad: { label: Actividad }
        username: { label: Usuario }
        user_id: { label: Usuario }
        concurso_tipo_id: { label: Tipo de concurso }
        created_at: { label: Creado el }
      list:
        max_per_page: 25
        sort: created_at
        title: Listado de Planes de acción
        #display: [_concurso_created_at, resume_name, resume_concurso, concurso_categoria, concurso_empresa, concurso_actividad, username, concurso_estado]
        display: [_concurso_created_at, resume_name, resume_concurso, concurso_categoria, username, concurso_estado]
        table_method: doSelectJoinCuncurso
        object_actions:
          show:
            action: show
            label: Ver        
          _edit:         ~
          _delete:       ~
        actions: {}
      filter:
        class: PlanesDeAccionEmpresaFormFilter
        #display: [created_at, name, concurso, concurso_categoria, concurso_empresa, user_id, concurso_estado]
        display: [ created_at, name, concurso_id, concurso_tipo_id, concurso_categoria, user_id, concurso_estado]
      form:    ~
      edit:    ~
      new:     ~
