<?php

/**
 * Alertas
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
sfProjectConfiguration::getActive()->loadHelpers(array('Date', 'Url'));

class Alertas extends BaseAlertas {

    public function getUser() {
        if ($this->getUserRelatedId()) {
            if ($user = Doctrine::getTable('sfGuardUser')->findOneBy('id', $this->getUserRelatedId()))
                return $user->getUsername();
        }
    }

    public function getMessageWithoutHtml() {
        return str_replace('&nbsp;', '', strip_tags($this->getMessage()));
    }

    /**
     * insert Alertas record into db from given parameters
     * @param String $user_id User Id
     * @param String $message Message
     * @param String $type Alert Type
     */
    public function create($user_id, $message, $type, $entity = 2) {
        //set attributs
        $this->setUserRelatedId($user_id);
        $this->setMessage($message);
        $this->setType($type);
        $this->setEntity($entity);
        //insert record into db
        $this->save();
    }

    public static function saveNewProfesionalAlerts($profesionalId) {
        $oAlerta = new Alertas();
        $oAlerta->setEntity(3);
        $oAlerta->setType('Nuevo profesional');
        $oAlerta->setMessage('Se ha dado de alta un profesional');
        $oAlerta->save();

        $oAlerta = new Alertas();
        $oAlerta->setEntity(4);
        $oAlerta->setType('Nuevo profesional');
        $oAlerta->setMessage('Se ha dado de alta un nuevo <a href="profesionalLista/show?id=' . $profesionalId . '">profesional</a> en el Directorio.');
        $oAlerta->save();

        $profesionalData = Doctrine::getTable('Profesional')->find($profesionalId);

        $ssProfFullName = $profesionalData->getFirstName() . ' ' . $profesionalData->getLastNameOne() . ' ' . $profesionalData->getLastNameTwo();

        $ssDate = format_datetime($profesionalData->getCreatedAt(), "HH:mm d/M/y") . '<strong> <a href="' . ("profesionalLista/show") . '?id=' . $profesionalData->getId() . '">' . ($ssProfFullName) . '</a>, </strong>';

        $ssDate .= $profesionalData->getCity()->getName();

        $ssDate .= cp::isStateCapital($profesionalData->getStates()->getName(), $profesionalData->getCity()->getName()) ? ', ' : ' (' . $profesionalData->getStates()->getName() . '), ';

        $ssDate .= $profesionalData->getUser()->getUsername() . '.';

        $oAlerta = new Alertas();
        $oAlerta->setEntity(7);
        $oAlerta->setType('Nuevo profesional');
        $oAlerta->setMessage($ssDate);
        $oAlerta->save();
    }

    public static function deleteProfesionalAlerts($profesionalId) {
        $q = 'profesionalLista/show?id=' . $profesionalId;
        $delete_query = Doctrine_Query::create()
                ->delete()
                ->from('Alertas a')
                ->whereIn('a.entity', array('3', '4', '7'))
                ->andWhere("a.message LIKE '%" . $q . "%'")
                ->andWhere("a.type = 'Nuevo profesional'");
        // execute delete query
        $delete_query->execute();
    }

    public static function generateRatioAlert($profesional) {
        $alert = 'Ei profesional ' . $profesional->getFirstName() . ' ' . $profesional->getLastNameOne() . ' ' . $profesional->getLastNameTwo()
                . ' de la actividad ' . $profesional->getActivityName() . ' en ' . (cp::isStateCapital($profesional->getStates()->getName(), $profesional->getCity()->getName()) ? $profesional->getCity()->getName() . ', ' : ' (' . $profesional->getStates()->getName() . ')') . '.';

        $oAlerta = new Alertas();
        $oAlerta->setEntity(12);
        $oAlerta->setType('Disaproval Ratio');
        $oAlerta->setMessage($alert);
        $oAlerta->save();
    }

    public static function despRatioAlert($profesional, $profesionalId) {
        $ssProfFullName = $profesional->getFirstName() . ' ' . $profesional->getLastNameOne() . ' ' . $profesional->getLastNameTwo();
        $ssApproval = 'El profesional ' . $ssProfFullName . ' ha bajado su <a href=/backend.php/profesionales/' . $profesionalId . '><strong>rendimiento</strong>.</a>';

        $oAlerta = new Alertas();
        $oAlerta->setEntity(10);
        $oAlerta->setType('Desaprobación');
        $oAlerta->setMessage($ssApproval);
        $oAlerta->save();
    }

    public static function recRatioAlert($profesional, $profesionalId) {
        $ssProfFullName = $profesional->getFirstName() . ' ' . $profesional->getLastNameOne() . ' ' . $profesional->getLastNameTwo();
        $ssApproval = 'El profesional ' . $ssProfFullName . ' ha bajado su <a href=/backend.php/profesionales/' . $profesionalId . '><strong>rendimiento</strong>.</a>';

        $oAlerta = new Alertas();
        $oAlerta->setEntity(8);
        $oAlerta->setType('Recomendación');
        $oAlerta->setMessage($ssApproval);
        $oAlerta->save();
    }

}

