<?php

/**
 * Auditanos
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Auditanos extends BaseAuditanos {

    public function getCpMunicipioProvincia($user_id) {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $html = '';

        $state_id = Doctrine_Query::create()
                ->select('states_id')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $city_id = Doctrine_Query::create()
                ->select('city_id')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $states = Doctrine::getTable('States')->find($state_id);
        $city = Doctrine::getTable('City')->find($city_id);

        if($states && $city_id)
        {
          if ($city_id == '') {
              $html .= $states->getName();

              return $html;
          }
          if ($city->getIsCapital()) {
              $html .= $city->getName();

              return $html;
          } else {
              $html .= $city->getName() . ' (';
              $html .= $states->getName() . ')';
              return $html;
          }

          return $city->getName();
        }

        return null;
    }

    public function getUserNames($user_id) {
        $user = Doctrine::getTable('SfGuardUser')->find($user_id);
        return $user->getUsername();
    }

    public function getProvincia($user_id) {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $state_id = Doctrine_Query::create()
                ->select('states_id')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $states = Doctrine::getTable('States')->find($state_id);
        if($states)
          return $states->getName();
        else
          return null;
    }

    public function getLoacalidad($user_id) {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $city_id = Doctrine_Query::create()
                ->select('city_id')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $city = Doctrine::getTable('City')->find($city_id);

        return $city->getName();
    }

    public function getLoacalidadObject($user_id) {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $city_id = Doctrine_Query::create()
                ->select('city_id')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $city = Doctrine::getTable('City')->find($city_id);

        return $city;
    }

    public function getJerarquia($user_id) {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $hierarchy_id = Doctrine_Query::create()
                ->select('hierarchy')
                ->from('sfGuardUserProfile p')
                ->where('p.id = ?', $user_id)
                ->execute(null, DOCTRINE::HYDRATE_SINGLE_SCALAR);

        $hierarchy = Doctrine::getTable('Jerarquia')->find($hierarchy_id);

        return $hierarchy->getName();
    }

}