<?php

/**
 * AuditanosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuditanosTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object AuditanosTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Auditanos');
  }

  /**
   * Fetch auditanos records
   * @param String $user_id User Id
   * @return Array
   */
  public function getAuditanosRecords($user_id) {
    //create auditanos records query
    $auditanos_records_query = Doctrine_Query::create()
            ->from('Auditanos a')
            ->where('a.user_id =?', $user_id)
            ->andWhere('a.status = 3');
    //return records
    return $auditanos_records_query->fetchArray();
  }

  /**
   * Join as doSelectJoinStatesLocationHeirarchyUsername
   * @param type $query
   * @return type 
   */
  public static function doSelectJoinStatesLocationHeirarchyUsername($query) {
    $rootAlias = $query->getRootAlias();
    return $query = $query->select($rootAlias . '.*, sgu.username')->leftJoin($rootAlias . '.sfGuardUser sgu');
    $query->leftJoin('sgu.User sgup');
    $query->leftJoin('sgup.City c');
  }

}