<?php

/**
 * ColaboradorNivelUnoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColaboradorNivelUnoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColaboradorNivelUnoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColaboradorNivelUno');
    }
}