<?php

/**
 * ConcursoReferendumCpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoReferendumCpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoReferendumCpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcursoReferendumCp');
    }
}