<?php

/**
 * ConcursoCpArchivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoCpArchivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoCpArchivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcursoCpArchivo');
    }
}