<?php

/**
 * ConcursoRevisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoRevisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoRevisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcursoRevision');
    }
}