<?php

/**
 * ConcursoTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcursoTipo');
    }
    
    public function getTipoId(){
      $tipo_query = Doctrine_Query::create()
                                ->from('ConcursoTipo ct');
      $tipo_records = $tipo_query->fetchArray();
      $tipo_array = array();
      foreach($tipo_records as $tipo_record){
        $tipo_array[$tipo_record['name']] = $tipo_record['id'];
      }
      return $tipo_array; 
    }
}