<?php

/**
 * ContactanosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactanosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactanosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contactanos');
    }
}