<?php

/**
 * ContribucionCpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContribucionCpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContribucionCpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContribucionCp');
    }
}