<?php

/**
 * Contratanos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contratanos extends BaseContratanos {

    public function save(Doctrine_Connection $conn = null) {
        if ($this->getCreatedAt() == "") {
            $this->setCreatedAt(date('Y-m-d H:i:s'));
        }
        parent::save($conn);
    }

    public function getCpMunicipioProvincia() {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $html = '';
        $state = Doctrine::getTable('States')->find($this->getStatesId());
        $city = Doctrine::getTable('City')->find($this->getCityId());

        if ($this->getCityId() == '') {
            $html .= $state->getName();

            return $html;
        }

        if ($city->getIsCapital()) {
            $html .= $city->getName();

            return $html;
        } else {
            $html .= $city->getName() . ' (';
            $html .= $state->getName() . ')';
            return $html;
        }

        return $city->getName();
    }

}