<?php

/**
 * CuestionarioBajaValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuestionarioBajaValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuestionarioBajaValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CuestionarioBajaValue');
    }
}