<?php

/**
 * EmpresaSectorTres
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmpresaSectorTres extends BaseEmpresaSectorTres {

  public function __toString() {
    return (string) $this->getName();
  }

  public function setSlug() {
    $slug = functions::toSlug($this->getName());
    return $this->_set('slug', $slug);
  }

//    public function setEmpresaSectorUnoId()
//    {
//        // No se puede setear este valor de forma individual.
//        // Se actualiza automaticamente al actualizar el campo empresa_sector_dos_id
//    }
//
//    public function setEmpresaSectorDosId($arg) {
//        $e2 = $arg instanceof EmpresaSectorDos ? $arg : Doctrine_Core::getTable('EmpresaSectorDos')->find($arg);
//        if ($e2)
//        {
//            $e1 = $e2->getEmpresaSectorUno();
//            if ($e1)
//            {
//                ldd($e1);
//                print 'd';  print ' *-'.$e2->getId().'--'.$e1->getId().'-* ';
//
////            $e1 = new EmpresaSectorDos();  $e1->get($e1)
//
//                $this->_set('empresa_sector_dos_id', $e2->getId());
//                $this->_set('empresa_sector_uno_id', $e1->getId());
//            }
//        } print '== ';
//    }
}
