<?php

/**
 * EmpresaSectorTresTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpresaSectorTresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpresaSectorTresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpresaSectorTres');
    }

    /**
     * Devuelve el nombre legible del
     * @static
     * @param $slug
     */
    public static function getName($slug)
    {
        $q = self::getInstance()->createQuery('q')
            ->select('q.name')
            ->where('q.slug = ?', $slug);
        return $q->fetchOne();
    }
    
    public function getSectoresTresOrderByOrden()
    {
        $elements  = $this->createQuery()->orderBy('orden')->execute();
    
        return $elements;
    }
}