<?php

/**
 * FormacionAcademicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormacionAcademicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormacionAcademicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormacionAcademica');
    }
}