<?php

/**
 * GanadoresConcursosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GanadoresConcursosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GanadoresConcursosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GanadoresConcursos');
    }
}