<?php

/**
 * GiftFavouriteListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftFavouriteListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftFavouriteListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GiftFavouriteList');
    }
    
    /**
     * fetch favourit gift record
     * @param String $user_id User Id
     * @param String $compnay_id Company Id
     * @return Record
     */
    public function getRecordByUserAndId($user_id, $gift_id){
      //create favourit query
      $favourit_query = Doctrine_Query::create()
                        ->from('GiftFavouriteList gfl')
                        ->where('gfl.user_id =?', $user_id)
                        ->andWhere('gfl.gift_id =?', $gift_id);
      //return favourit record
      return $favourit_query->fetchOne();
                
    }
}