<?php

/**
 * GiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gift');
    }
    
    /**
     * method will return gift query
     * @return Doctrine_Query
     */
    public function getGiftQuery(){
      //create gift query
      $gift_query = Doctrine_Query::create()
                                  ->from('gift g')
                                  ->orderBy('g.orden ASC');
      //return gift query
      return $gift_query;
    }
    
    /**
     * returns featured gift records
     * @return Array
     */
    public function getFeaturedGiftList(){
      //create gift query
      $gift_query = Doctrine_Query::create()
                                  ->from('gift g')
                                  ->where('g.featured = 1' )
                                  ->limit(6)
                                  ->orderBy('g.featured_order ASC, g.created_at DESC');
      $gift_records = $gift_query->fetchArray();
      return $gift_records;
    }
    
    /**
     * fetch query for gift favourit list for given user id
     * @param String $user_id User id
     * @return Doctrine_Query
     */
    public function getFavouritGift($user_id){
      //create gift favourit list query
      $gift_favourit_list_query = Doctrine_Query::create()
                                   ->from('Gift g')
                                   ->leftJoin('g.GiftFavouriteList gfl')
                                   ->where('gfl.user_id =?', $user_id)
                                   ->orderby('gfl.created_at DESC');
      //return query
      return $gift_favourit_list_query;
      
    }

    /**
     * Fetch the gift featured limit
     * It will help Admin to publish gift on home page
     * if gift featured limit is not more than 10
     * @param $list_type List Type
     * @return Array
     */
    public function getFeatreudLimit($list_type = 'lb'){
      //create gift featured limit query
      $gift_feature_limit_query = Doctrine_Query::create()
                                                    ->select('COUNT(g.id) gift_limit')
                                                    ->from('Gift g')
                                                    ->where('g.featured = 1');
      //fetch limit
      return $gift_feature_limit_query->fetchArray();
    }
}