<?php

/**
 * JerarquiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JerarquiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JerarquiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jerarquia');
    }
    
    /**
     * return Hierarchy list in Array format
     * @return Array
     */
    public function getHierarchyList(){
      //create hierarchy list query
      $hierarchy_list_query = Doctrine_Query::create()
                                             ->select('h.name')
                                             ->from('Jerarquia h')
                                             ->orderBy('h.points asc');
     $hierarchy_list = $hierarchy_list_query->fetchArray();
     $hierarchy_record = array();
     foreach ($hierarchy_list as $index => $record){
       $hierarchy_record[$record['id']] = $record['name'];
     }
     return $hierarchy_record;
    }
}