<?php

/**
 * KpiEmpresaProducto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KpiEmpresaProducto extends BaseKpiEmpresaProducto
{

    /**
     * Añade el valor y recalcula la media...
     *
     * @param $value
     */
    public function addValue($value)
    {
        $this->setNumeroValores($this->getNumeroValores() + 1);
        $this->setSumaValores($this->getSumaValores() + $value);

        $this->save();
    }

    public function getMedia()
    {
        if($this->getNumeroValores() == 0) {
            return 0;
        }
        $media = $this->getSumaValores() / $this->getNumeroValores();
        return round($media, 2);
    }

    /**
     * @param $value
     */
    public function substractValue($value)
    {
        $this->setNumeroValores($this->getNumeroValores() - 1);
        $this->setSumaValores($this->getSumaValores() - $value);

        $this->save();
    }
}
