<?php

/**
 * KpiEmpresaProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KpiEmpresaProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KpiEmpresaProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KpiEmpresaProducto');
    }

    public function findByEmpresaIdAndKpiId($empresa_id, $kpi_id)
    {
        $q = $this->createQuery('q')
            ->where('q.empresa_id = ?', $empresa_id)
            ->andWhere('q.kpi_id = ?', $kpi_id)
            ;

        return $q->fetchOne();
    }

    public function findByProductoIdAndKpiId($producto_id, $kpi_id)
    {
        $q = $this->createQuery('q')
            ->where('q.producto_id = ?', $producto_id)
            ->andWhere('q.kpi_id = ?', $kpi_id)
        ;

        return $q->fetchOne();
    }
}