<?php

/**
 * ListaCuestionarioPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ListaCuestionarioPregunta extends BaseListaCuestionarioPregunta {

    /**
     * Esto queda muy mal pero sinó en el embed form pone un número por defecto...
     * @return string
     */
    public function __toString() {
        return $this->getPregunta();
    }

    public function getPreguntaString() {
        $pregunta = Doctrine_Core::getTable('ListaCuestionarioPregunta')->find($this->getPregunta());
        if (!$pregunta)
            return $this->getPregunta();
        else
            return $pregunta->getPregunta();;
    }

}
