<?php

/**
 * MesaredondaReferendumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MesaredondaReferendumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MesaredondaReferendumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MesaredondaReferendum');
    }
}