<?php

/**
 * MesaredondaCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MesaredondaCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MesaredondaCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MesaredondaCategoria');
    }
}