<?php

/**
 * MetodoPaypalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetodoPaypalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetodoPaypalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetodoPaypal');
    }
}