<?php

/**
 * PdAproDesproTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PdAproDesproTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PdAproDesproTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PdAproDespro');
    }
}