<?php

/**
 * PizarraSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PizarraSectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PizarraSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PizarraSection');
    }
    
    /**
     * return pizarra section list
     * @return Array
     */
    public function getSectionList(){
      //create section list query
      $section_list_query = Doctrine_Query::create()
                                          ->from('PizarraSection ps')
                                          ->orderBy('ps.short_name ASC');
      $section_list_records = $section_list_query->fetchArray();
      $section_list =array();
      foreach($section_list_records as $index => $section_record){
        $section_list[$section_record['id']]= $section_record['short_name'];
      }
      
      return $section_list;
    }
}