<?php

/**
 * PizarraSectionMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PizarraSectionMapping extends BasePizarraSectionMapping
{

  /**
   * create pizarra scrtion mapping record
   * @param String $pizarra_id
   * @param String $section_id
   */
  public function create($pizarra_id, $section_id){
    //set attribute 
    $this->setPizarraId($pizarra_id);
    $this->setPizarraSectionId($section_id);
    $this->setCreatedAt(date('Y-m-d H:i:s'));
    //insert record into db
    $this->save();
  }
}