<?php

/**
 * ProductCaseStudy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCaseStudy extends BaseProductCaseStudy {

  public function getTipo() {
    return $this->getProductoTipoTres()->getId() ? $this->getProductoTipoTres() : $this->getProductoTipoDos();
  }
  
  public function getTipoName() {
      return  ($this->getProductoTipoTres() && $this->getProductoTipoTres()->getId()) ? $this->getProductoTipoTres() : '';
  }

  public function getTipoId() {
    return $this->getTipo()->getId();
  }

  /**
   * Fecth Product sector
   * @return String
   */
  public function getSector() {
    return $this->getProductoTipoUno()->getId() ? $this->getProductoTipoUno() : '';
  }

  /**
   * Fecth Product sub sector
   * @return String
   */
  public function getSubSector() {
    return $this->getProductoTipoDos()->getId() ? $this->getProductoTipoDos() : '';
  }
  
   /**
     * Get Created at with format
     * @param type $format 
     */
    public function getFCreatedAt($format = 'D, d M Y H:i:s') {
        echo date($format, strtotime($this->getCreatedAt()));
    }

}