<?php

/**
 * ProductoTipoTresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTipoTresTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTipoTresTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductoTipoTres');
    }

    /**
     * Devuelve el nombre legible del
     * @static
     * @param $slug
     */
    public static function getName($slug) {
        $q = self::getInstance()->createQuery('q')
                ->select('q.name')
                ->where('q.slug = ?', $slug);
        return $q->fetchOne();
    }

}