<?php

/**
 * ProfesionalTipoDosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionalTipoDosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionalTipoDosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfesionalTipoDos');
    }
    
    /**
     * Devuelve el nombre legible del slug
     * @static
     * @param $slug
     */
    public static function getName($slug)
    {
        $q = self::getInstance()->createQuery('q')
            ->select('q.name')
            ->where('q.slug = ?', $slug);
        return $q->fetchOne();
    }

    /**
     * Comprueba si el sector dos tiene actividad asociada.
     * @static
     * @param $sector_dos_id
     */
    public static function hasActividad($sector_dos_id)
    {
        $q = Doctrine_Core::getTable('ProfesionalTipoTres')->createQuery('q')
           ->where('q.profesional_tipo_dos_id = ?', $sector_dos_id);

        return $q->count() > 0 ? true : false;
    }
    
    public function getSectoresDosOrderByOrden()
    {
        $elements  = $this->createQuery()->orderBy('orden')->execute();
    
        return $elements;
    }

    /**
     * Function for ordering in listitng page of 'Subsector profesionals'
     * @static
     * @param $query
     */
    public static function doSelectJoinSector($query)
    {
      return $query->select('r.*, ptu.name')
        ->leftJoin('r.ProfesionalTipoUno ptu');
    }
}
