<?php

/**
 * ProfesionalTipoUnoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionalTipoUnoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionalTipoUnoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfesionalTipoUno');
    }
    
    /**
     * Devuelve el nombre legible del
     * @static
     * @param $slug
     */
    public static function getName($slug)
    {
        $q = self::getInstance()->createQuery('q')
            ->select('q.name')
            ->where('q.slug = ?', $slug);
        return $q->fetchOne();
    }

    public function getQueryProfesionalTipoUno()
    {
        $q = $this->createQuery('a')
            ->leftJoin('a.ProfesionalTipoDos p2')
            ->leftJoin('p2.ProfesionalTipoTres');

        return $q;
    }

    public function getProfesionalTipoUno()
    {
        return $this->getQueryProfesionalTipoUno()->execute();
    }
    
    public function getSectoresUnoOrderByOrden()
    {
      $elements  = $this->createQuery()->orderBy('orden')->execute();
      
      $arr=array();
      foreach ($elements as $v) {
        $arr[]=array('id'=>$v->getId(), 'value'=>$v->getName());
      }
      
      return $arr;
    }
}
