<?php

/**
 * ProfesionalLetterHistoricoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionalLetterHistoricoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionalLetterHistoricoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfesionalLetterHistorico');
    }
}