<?php

/**
 * ProfesionalDestacadosTemporalesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionalDestacadosTemporalesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionalDestacadosTemporalesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfesionalDestacadosTemporales');
    }
}