<?php

/**
 * RecomiendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecomiendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecomiendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Recomienda');
    }
    
    
    /**
     * update records as user is registered to system
     * @param type $user_id
     */
    public function updateForRegistration($user_id){
      //create update registration flag query
      $update_registration_flag_query = Doctrine_Query::create()
                                                      ->update('Recomienda r')
                                                      ->set('r.is_registerd', 1);
      //update records
      $update_registration_flag_query->execute();
    }
    
    /**
     * Fetch user recomended count
     * @param String $user_id User Id
     * @return int
     */
    public function getRecomendLimiFor($user_id){
      //create recomend limit query
      $current_date = date('Y');
      $recomende_limit_query = Doctrine_Query::create()
                ->select('COUNT(r.id) recomended_cout')
                ->from('Recomienda r')
                ->where('r.user_id =?', $user_id)
                ->andWhere('r.is_registerd = 1')
                ->andWhere('DATE_FORMAT(r.created_at,"%Y") = ' . $current_date);
      
      $recomende_limit_record = $recomende_limit_query->fetchArray();
      
      if($recomende_limit_record){
        return $recomende_limit_record[0]['recomended_cout'];
      }else{
        return 0;
      }
    }
    
    /**
     * Fetch recommended registered user
     * @param String $user_id User Id
     * @return Array
     */
    public function getRegisteredUser($user_id){
      //create registered user query
      $registered_user_query = Doctrine_Query::create()
                              ->from('Recomienda r')
                              ->where('r.user_id =?', $user_id)
                              ->andWhere('r.is_registerd = 1');
      //return records
      return $registered_user_query->fetchArray();
    }
}