<?php

/**
 * RewardLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RewardLog extends BaseRewardLog {

  /**
   * create reward log record from given User object and cash amount
   * @param Object $user sfGuardUser
   * @param String $hierarchy Contributors Hierarchy
   * @param String $amount Amount
   */
  public function create($user, $hierarchy, $amount, $gift = null) {
    //set parameters
    if ($gift) {
      $this->setDescroption('Canje de regalo');
    } else {
      $this->setDescroption('Ha hecho caja');
    }

    $this->setUserId($user->getId());
    if ($amount != null) {
      $this->setCash($amount);
    }
    if ($gift != null) {
      $this->setGift($gift);
    }
    $this->setCreatedAt(date('Y-m-d H:i:s'));
    $this->setHierarchy($hierarchy);
    //insert record to db
    $this->save();
  }

}