<?php

/**
 * sfGuardUserDataTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserData');
    }

    public static function getbyName($name)
    {
        $user = sfContext::getInstance()->getUser();
        if ($user->isAuthenticated())
        {
            $obj = self::getInstance()->findOneByUserIdAndName($user->getGuardUser()->getId(), $name);
            return $obj ? $obj->getUserData() : null;
        }
        else
        {
            return null;
        }
    }

    public static function setbyName($name, $data)
    {
        $user = sfContext::getInstance()->getUser();
        if ($user->isAuthenticated())
        {
            $obj = self::getInstance()->findOneByUserIdAndName($user->getGuardUser()->getId(), $name);
            if (!$obj)
            {
                $obj = new sfGuardUserData();
                $obj->setUserId($user->getGuardUser()->getId());
                $obj->setName($name);
            }

            $obj->setUserData($data);
            $obj->save();
        }
    }
}