<?php

/**
 * TipoTiempoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTiempoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTiempoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTiempo');
    }
}