<?php

/**
 * UserCompanyCaseStudyRequestTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCompanyCaseStudyRequestTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UserCompanyCaseStudyRequestTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UserCompanyCaseStudyRequest');
    }

    /**
     * Join as States EmpresaSectorUno EmpresaSectorDos EmpresaSectorTres Localidad
     * @param type $query
     * @return type 
     */
    public static function doSelectJoinSectors($query) {
        $rootAlias = $query->getRootAlias();
        $query = $query->select($rootAlias . '.*, esu.name')->leftJoin($rootAlias . '.EmpresaSectorUno esu');
        $query->select($rootAlias . '.*, esd.name')->leftJoin($rootAlias . '.EmpresaSectorDos esd');
        $query->select($rootAlias . '.*, c.name')->leftJoin($rootAlias . '.Localidad c');
        $query->select($rootAlias . '.*, s.name')->leftJoin($rootAlias . '.States s');
        return $query->select($rootAlias . '.*, est.name')->leftJoin($rootAlias . '.EmpresaSectorTres est');
    }

}