<?php

/**
 * UserCompanyCaseStudyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCompanyCaseStudyTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object UserCompanyCaseStudyTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('UserCompanyCaseStudy');
  }

  /**
   * Fetch user case study records
   * @param String $user_id User Id
   * @return Array
   */
  public function getCompanyCaseStudy($user_id) {
    //create company product case study query
    $company_product_case_study_query = Doctrine_Query::create()
            ->select('sgu.id,uccs.id, uccs.name company_name')
            ->from('UserCompanyCaseStudy uccs')
            ->leftJoin('uccs.User sgu')
            ->where('sgu.id =?', $user_id)
            ->andWhere('uccs.status = 3');
    
    //return recorsd
    return $company_product_case_study_query->fetchArray();
  }
  /**
     * Join as States EmpresaSectorUno EmpresaSectorDos EmpresaSectorTres Localidad
     * @param type $query
     * @return type 
     */
    public static function doSelectJoinSectors($query) {
        $rootAlias = $query->getRootAlias();
        $query = $query->select($rootAlias . '.*, esu.name')->leftJoin($rootAlias . '.EmpresaSectorUno esu');
        $query->select($rootAlias . '.*, esd.name')->leftJoin($rootAlias . '.EmpresaSectorDos esd');
        $query->select($rootAlias . '.*, c.name')->leftJoin($rootAlias . '.Localidad c');
        $query->select($rootAlias . '.*, s.name')->leftJoin($rootAlias . '.States s');
        return $query->select($rootAlias . '.*, est.name')->leftJoin($rootAlias . '.EmpresaSectorTres est');                
    }

}