<?php

/**
 * UserCompanyCaseStudyRequest
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserCompanyCaseStudyRequest extends BaseUserCompanyCaseStudyRequest {

    public function getCpMunicipioProvincia() {
        //si no hay localidad (caso solo para "toda españa") devuelve la provincia.
        $html = '';
        if ($this->getLocalidad()->getIsCapital()) {
            $html .= $this->getLocalidad();
            return $html;
        } else {
            $html .= $this->getLocalidad() . ' (';
            $html .= $this->getStates() . ')';
            return $html;
        }
        return $this->getLocalidad();
    }

    /**
     * Get Created at with format
     * @param type $format
     */
    public function getFCreatedAt($format = 'D, d M Y H:i:s') {
        echo date($format, strtotime($this->getCreatedAt()));
    }

}