<?php

/**
 * UserNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserNotification extends BaseUserNotification
{
	public function getConcursoEmpresaCiudadId()
	{
		if($this->getConcursoEmpresaProvinciaId()==16)	//ceuta
			return 5884;
		elseif($this->getConcursoEmpresaProvinciaId()==35)	//melilla
			return 5885;
		elseif($this->getConcursoEmpresaProvinciaId()==1)	//melilla
			return 8113;			
		else
			return $this->_get('concurso_empresa_ciudad_id');
	}
}
