OrderPreferences:
  options:
    symfony:
      form:   false
      filter: false

  columns:
    sf_guard_user_id: integer
    key_id: string(255)
    orden: longtext
  indexes:
    idx_key:
      fields: [ key_id ]
  relations:
    sfGuardUser:
      alias: User
      foreignAlias: orderPreferences



