# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [global.css,concurso.css,estyl_sup.css,pagination.css,buscador.css]
  javascripts:    [jquery-1.7.2.min.js, jquery.autocompleter.js,close_flash.js, tiny_mce/tiny_mce.js]

  has_layout:     true
  layout:         layout_concurso
  
showincidenciadescripcionSuccess:
  layout:         false
  
showresumenplandeaccionSuccess:
  layout:         false
  
showplandeaccionSuccess:
  layout:         false    