generator:
  class: sfDoctrineGenerator
  param:
    model_class:           auditanos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          auditanos
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: 
        _new: { label: 'Nuevo formulario' }
      fields:  
        created_at : { label: 'Creado el' }
        username : { label: 'Usuario', sortBy : username }
        heirarchy : { label: 'Jerarquía'}
        state : { label: 'Provincia'}
        location : { label: 'Localidad' }
        status: { label: 'Estado'}
        usuario: { label: 'Usuario' }
      list:   
        max_per_page: 25
        title: Listado de formulario de Audítanos
        display: [ _created_at, _state, _location, _heirarchy ,_username, _status]
        table_method: doSelectJoinStatesLocationHeirarchyUsername
        object_actions:
          _ver: { label: ver, action: show}
          _edit: ~
          _delete: ~
          _processed: { label: Tramitado, action: processed}
          _closed: { label: Cerrado , action: closed}
          
      filter:  
        display: [created_at, user_id, states_id, city_id, hierarchy, status]
        fields:  
          user_id : { label: 'Usuario' }
          states_id : { label: 'Provincia'}
          location : { label: 'Localidad' }
      form:    ~
      edit:    
        title: Editar formulario de Audítanos
      new:     
        title: Nuevo formulario  de Audítanos
