generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Fichero
    theme:                 deneb
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fichero
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
         _new: { label: "Nuevo"}
      fields:  ~
      list:
        title: Ficheros con los documentos de cada concurso
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
